import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {db} from './db';
import {requirePermission} from './permissions';
import {AppError} from './errors';
import {mediaStorage,type MediaStorage} from './media-storage';
import {processImage} from './media-processing';
import {lockMedia,references} from './media-references';
export async function reserveUpload(actorId:string|null){await requirePermission(actorId,'manage_media');const rows=await db.$queryRaw<{count:number}[]>`INSERT INTO "MediaUploadQuota" ("actorId","windowStart","count") VALUES (${actorId!},NOW(),1) ON CONFLICT ("actorId") DO UPDATE SET "windowStart"=CASE WHEN "MediaUploadQuota"."windowStart" < NOW()-INTERVAL '10 minutes' THEN NOW() ELSE "MediaUploadQuota"."windowStart" END,"count"=CASE WHEN "MediaUploadQuota"."windowStart" < NOW()-INTERVAL '10 minutes' THEN 1 ELSE "MediaUploadQuota"."count"+1 END RETURNING "count"`;if(rows[0].count>10)throw new AppError(429,'Upload limit reached. Try again in ten minutes.');}
type StockImport = {fileHash:string;stockIdentity:string;alt:string;source:Record<string,string|number|null>};
export async function uploadMedia(actorId:string|null,bytes:Buffer,filename:string,storage:MediaStorage=mediaStorage,stock?:StockImport){await requirePermission(actorId,'manage_media');const image=await processImage(bytes,filename,Boolean(stock));const id='media_'+randomUUID();const variants=Object.fromEntries(image.variants.map(v=>[v.name,{key:id+'/'+v.name+'.webp',width:v.width,height:v.height,size:v.data.length}]));try{await db.mediaAsset.create({data:{id,filename:image.filename,mimeType:image.mimeType,width:image.width,height:image.height,size:image.size,variants,creatorId:actorId!,...(stock?{fileHash:stock.fileHash,stockIdentity:stock.stockIdentity,alt:stock.alt,source:{...stock.source,importedWidth:image.width,importedHeight:image.height}}:{})}});}catch(error){if(stock&&typeof error==='object'&&error&&'code' in error&&error.code==='P2002')throw new AppError(409,'This stock image is already being imported or exists in the library. Refresh the library.');throw error;}
 try{for(const variant of image.variants)await storage.put(variants[variant.name].key,variant.data);return await db.$transaction(async tx=>{await requirePermission(actorId,'manage_media',tx);const ready=await tx.mediaAsset.update({where:{id},data:{state:'READY'}});await tx.auditLog.create({data:{actorId,entityType:'MediaAsset',entityId:id,action:'media.uploaded',after:{filename:ready.filename,mimeType:ready.mimeType,width:ready.width,height:ready.height,size:ready.size}}});return ready;});}
 catch(error){const results=await Promise.allSettled(Object.values(variants).map(v=>storage.remove(v.key)));if(results.every(r=>r.status==='fulfilled'))await db.mediaAsset.delete({where:{id}});else await db.mediaAsset.update({where:{id},data:{state:'CLEANUP'}});throw error;}
}
const updateSchema=z.object({expectedVersion:z.number().int().positive(),action:z.enum(['metadata','archive','recover','cleanup']),alt:z.string().trim().max(300).optional(),focalX:z.number().int().min(0).max(100).optional(),focalY:z.number().int().min(0).max(100).optional()}).strict();
export async function updateMedia(actorId:string|null,id:string,input:unknown,storage:MediaStorage=mediaStorage){await requirePermission(actorId,'manage_media');const data=updateSchema.parse(input);return db.$transaction(async tx=>{await requirePermission(actorId,'manage_media',tx);await lockMedia(tx);const item=await tx.mediaAsset.findUnique({where:{id}});if(!item)throw new AppError(404,'Image not found');if(item.version!==data.expectedVersion)throw new AppError(409,'This image changed. Refresh its details.');if(data.action==='cleanup'){if(item.state!=='CLEANUP'&&!(item.state==='PENDING'&&item.createdAt.getTime()<Date.now()-3600000))throw new AppError(400,'No cleanup is pending');for(const v of Object.values(item.variants as Record<string,{key:string}>))await storage.remove(v.key);await tx.mediaAsset.delete({where:{id}});await tx.auditLog.create({data:{actorId,entityType:'MediaAsset',entityId:id,action:'media.cleanup_completed'}});return {id};}if(item.state!=='READY')throw new AppError(409,'Image processing is not complete');if(data.action==='archive'){const refs=await references(id,tx);if(refs.published.length||refs.publications.length)throw new AppError(409,'This image is protected by a published snapshot.');if(refs.drafts.length)throw new AppError(409,'Replace this image in saved drafts before archiving.');}
 const next=await tx.mediaAsset.update({where:{id},data:{...(data.action==='metadata'?{alt:data.alt??item.alt,focalX:data.focalX??item.focalX,focalY:data.focalY??item.focalY}:{archivedAt:data.action==='archive'?new Date():null}),version:{increment:1}}});await tx.auditLog.create({data:{actorId,entityType:'MediaAsset',entityId:id,action:'media.'+data.action,before:{alt:item.alt,focalX:item.focalX,focalY:item.focalY,archived:!!item.archivedAt},after:{alt:next.alt,focalX:next.focalX,focalY:next.focalY,archived:!!next.archivedAt}}});return next;});}
