import {assertTestEnvironment} from '../scripts/test-environment';assertTestEnvironment();
import {test,after} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {db} from '../src/server/db';import {initializeIndustry} from '../src/server/industry-initialize';import {saveDraft,restoreDraft} from '../src/server/content';import {roofingHubFixture} from './fixtures/roofing-hub';import {industryDetailSchema} from '../src/schemas/industry-detail';import {industrySlugs,industryNames,isIndustrySlug,type IndustrySlug} from '../src/content/industry-registry';import {industryPageData} from '../src/server/industry-detail-page';import {beautyIndustrySnapshot} from '../src/content/beauty-industry-defaults';
test('Beauty defaults preserve the frozen Roofing 5 structure and approved content',()=>{const template=roofingHubFixture();const services=template.sections.find(s=>s.type==='services')!;while(services.items.length<8)services.items.push({...services.items[0],id:`roofing-services-${services.items.length+1}`});const faq=template.sections.find(s=>s.type==='faq')!;faq.items=faq.items.slice(0,5);const snapshot=beautyIndustrySnapshot({title:'Roofing',sections:[],industryDetail:template});const detail=snapshot.industryDetail!;assert.equal(snapshot.title,'Beauty, Skincare & Med Spa');assert.equal(detail.slug,'beauty-skincare-med-spa');assert.equal(detail.hero.title,'Beauty, Skincare & Med Spa');assert.deepEqual(detail.sections.map(s=>s.type),template.sections.map(s=>s.type));assert.equal(detail.sections.find(s=>s.type==='services')?.items.length,8);assert.equal(detail.sections.find(s=>s.type==='faq')?.items.length,5);assert.equal(detail.sections.find(s=>s.type==='faq')?.destination,'https://codeyea.com/contact/');assert.equal(detail.seo?.title,'Beauty, Skincare & Med Spa Digital Services | CODEYEA');});
test('every industry preserves template section structure and rejects mismatched stable identities',()=>{for(const slug of industrySlugs){const detail=roofingHubFixture();detail.slug=slug;detail.hero.title=industryNames[slug];detail.sections.forEach(s=>s.id=slug+'-'+s.type);assert.equal(industryDetailSchema.safeParse(detail).success,true);detail.sections[0].id='wrong-overview';assert.equal(industryDetailSchema.safeParse(detail).success,false);}});
test('Beauty, Skincare & Med Spa uses the frozen template contract and stays unavailable publicly while draft-only',async()=>{
 const slug='beauty-skincare-med-spa' as IndustrySlug;assert.equal(isIndustrySlug(slug),true);assert.equal(industryNames[slug],'Beauty, Skincare & Med Spa');
 const actor='beauty-industry-test-'+randomUUID();const template={title:'Roofing',sections:[],industryDetail:roofingHubFixture()};await db.user.create({data:{id:actor,email:actor+'@example.test',name:'Beauty industry editor',roles:{create:{roleId:'administrator'}}}});await db.page.create({data:{id:'roofing',slug:'industries/roofing',title:'Roofing',version:5,localeId:'en',marketId:'global',draftSnapshot:template}});
 try{const detail=structuredClone(template.industryDetail);detail.slug=slug;detail.hero.title=industryNames[slug];detail.sections.forEach(s=>s.id=slug+'-'+s.type);const snapshot={title:industryNames[slug],sections:[],industryDetail:detail};const created=await initializeIndustry(actor,{pageId:slug,templateVersion:5,snapshot});assert.equal(created.version,1);assert.equal(created.publishedSnapshot,null);assert.ok(await industryPageData(slug,true));assert.equal(await industryPageData(slug),null);assert.equal(await db.pageRevision.count({where:{pageId:slug,version:1}}),1);assert.equal(await db.auditLog.count({where:{entityId:slug,actorId:actor,action:'page.draft_initialized'}}),1);
 }finally{await db.page.deleteMany({where:{id:{in:[slug,'roofing']}}});await db.auditLog.deleteMany({where:{actorId:actor}});await db.user.delete({where:{id:actor}});}
});
test('independent industry draft initialization, stale-save rejection and restore remain private',async()=>{
 const actor='industry-test-'+randomUUID();const template={title:'Roofing',sections:[],industryDetail:roofingHubFixture()};await db.user.create({data:{id:actor,email:actor+'@example.test',name:'Industry editor',roles:{create:{roleId:'administrator'}}}});
 await db.page.create({data:{id:'roofing',slug:'industries/roofing',title:'Roofing',version:5,localeId:'en',marketId:'global',draftSnapshot:template}});
 try{const detail=structuredClone(template.industryDetail);detail.slug='healthcare';detail.hero.title='Healthcare';detail.sections.forEach(s=>s.id='healthcare-'+s.type);const snapshot={title:'Healthcare',sections:[],industryDetail:detail};const input={pageId:'healthcare' as const,templateVersion:5 as const,snapshot};await assert.rejects(initializeIndustry(null,input),/Unauthorized/);const created=await initializeIndustry(actor,input);assert.equal(created.publishedSnapshot,null);assert.equal(created.version,1);await assert.rejects(initializeIndustry(actor,input),/already/);
 const next=await saveDraft(actor,{...snapshot,title:'Healthcare',industryDetail:{...detail,seo:{title:'Healthcare | CODEYEA',description:'Practical healthcare website information.'}},pageId:'healthcare',expectedVersion:1});assert.equal(next.version,2);await assert.rejects(saveDraft(actor,{...snapshot,pageId:'healthcare',expectedVersion:1}),/changed/);const rev=await db.pageRevision.findFirstOrThrow({where:{pageId:'healthcare',version:1}});const restored=await restoreDraft(actor,{pageId:'healthcare',revisionId:rev.id,expectedVersion:2});assert.equal(restored.publishedSnapshot,null);assert.deepEqual(restored.draftSnapshot,snapshot);assert.deepEqual((await db.page.findUniqueOrThrow({where:{id:'roofing'}})).draftSnapshot,template);
 }finally{await db.page.deleteMany({where:{id:{in:['healthcare','roofing']}}});await db.auditLog.deleteMany({where:{actorId:actor}});await db.user.delete({where:{id:actor}});}
});
after(async()=>db.$disconnect());
