import {assertTestEnvironment} from '../scripts/test-environment';assertTestEnvironment();
import {before,after,test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import sharp from 'sharp';import {db} from '../src/server/db';import {uploadMedia,updateMedia,reserveUpload} from '../src/server/media';import type {MediaStorage} from '../src/server/media-storage';import {references,isPublicMedia} from '../src/server/media-references';import {saveDraft,restoreDraft} from '../src/server/content';import {publishDraft} from '../src/server/publishing';import {defaultHomepage} from '../src/content/homepage-defaults';import type {EditorObject} from '../src/schemas/homepage-editor';
const key=randomUUID(),owner='media-owner-'+key,editor='media-editor-'+key,pageId='media-page-'+key;let bytes:Buffer;const files=new Map<string,Buffer>();const store:MediaStorage={async put(k,b){if(files.has(k))throw new Error('Collision');files.set(k,b)},async get(k){const b=files.get(k);if(!b)throw new Error('Missing');return b},async remove(k){files.delete(k)}};
const original={title:'Media isolated page',sections:[{id:'media-section-'+key,type:'positioning' as const,heading:'Original heading',body:'Original body'}]};
test('stock imports persist provenance, enforce both duplicate constraints and retain archive/audit protections',async()=>{
 const stock={fileHash:'hash-'+key,stockIdentity:'pexels:'+key,alt:'A test image',source:{provider:'pexels',providerId:key,sourcePageUrl:'https://www.pexels.com/photo/test/',contributor:'Test contributor',originalWidth:800,originalHeight:400,importedAt:new Date().toISOString(),licenseLabel:'Pexels License',query:'test',approvalStatus:'temporary-stock'}};
 const asset=await uploadMedia(owner,bytes,'stock.png',store,stock);assert.equal(asset.alt,stock.alt);assert.equal(asset.stockIdentity,stock.stockIdentity);assert.equal((asset.source as any).approvalStatus,'temporary-stock');assert.equal((asset.source as any).importedWidth,800);assert.equal(Object.keys(asset.variants as object).length,4);
 await assert.rejects(uploadMedia(owner,bytes,'same-provider.png',store,{...stock,fileHash:'different-'+key}),/already/);
 await assert.rejects(uploadMedia(owner,bytes,'same-hash.png',store,{...stock,stockIdentity:'pixabay:'+key}),/already/);
 await updateMedia(owner,asset.id,{action:'archive',expectedVersion:1},store);await updateMedia(owner,asset.id,{action:'recover',expectedVersion:2},store);
 const restored=await db.mediaAsset.findUniqueOrThrow({where:{id:asset.id}});assert.deepEqual(restored.source,asset.source);assert.equal(await db.auditLog.count({where:{entityId:asset.id}}),3);
});
before(async()=>{bytes=await sharp({create:{width:800,height:400,channels:3,background:'#10aabc'}}).png().toBuffer();for(const [id,role] of [[owner,'administrator'],[editor,'editor']])await db.user.create({data:{id,name:id,email:id+'@example.test',roles:{create:{roleId:role}}}});await db.page.create({data:{id:pageId,slug:pageId,title:original.title,localeId:'en',marketId:'global',publishedSnapshot:original,sections:{create:{...original.sections[0],position:0}}}});});
after(async()=>{await db.page.deleteMany({where:{id:pageId}});await db.auditLog.deleteMany({where:{actorId:{in:[owner,editor]}}});await db.mediaAsset.deleteMany({where:{creatorId:owner}});await db.mediaUploadQuota.deleteMany({where:{actorId:{in:[owner,editor]}}});await db.user.deleteMany({where:{id:{in:[owner,editor]}}});await db.$disconnect();});
test('uploads enforce media permission and account quotas',async()=>{await assert.rejects(uploadMedia(null,bytes,'photo.png',store),/Unauthorized/);await assert.rejects(uploadMedia(editor,bytes,'photo.png',store),/Forbidden/);for(let i=0;i<10;i++)await reserveUpload(owner);await assert.rejects(reserveUpload(owner),/limit/);await assert.rejects(reserveUpload(editor),/Forbidden/);});
test('duplicate names retain immutable distinct keys, metadata versions and audit attribution',async()=>{const a=await uploadMedia(owner,bytes,'../../same.png',store),b=await uploadMedia(owner,bytes,'same.png',store);assert.notEqual(a.id,b.id);assert.equal(a.filename,'same.png');assert.equal(a.width,800);assert.equal(a.mimeType,'image/png');assert.equal(Object.keys(a.variants as object).length,4);const next=await updateMedia(owner,a.id,{action:'metadata',expectedVersion:1,alt:'New alternative',focalX:20,focalY:70},store);assert.equal('alt' in next&&next.alt,'New alternative');await assert.rejects(updateMedia(owner,a.id,{action:'metadata',expectedVersion:1,alt:'Stale'},store),/changed/);await assert.rejects(updateMedia(owner,a.id,{action:'metadata',expectedVersion:2,focalX:101},store));assert.equal(await db.auditLog.count({where:{entityId:a.id,actorId:owner}}),2);assert.equal(await isPublicMedia(a.id),false);});
test('draft and metadata changes stay private; published and historical references protect files',async()=>{const asset=await uploadMedia(owner,bytes,'isolated.png',store);const homepage=defaultHomepage() as unknown as Record<string,EditorObject>;homepage.hero.media={mediaId:asset.id,alt:'Draft alternative',decorative:false,focalX:50,focalY:50,width:asset.width,height:asset.height};const saved=await saveDraft(owner,{...original,homepage,pageId,expectedVersion:1});assert.deepEqual(saved.publishedSnapshot,original);assert.equal(await isPublicMedia(asset.id),false);assert.equal((await references(asset.id)).drafts.length,1);await assert.rejects(updateMedia(owner,asset.id,{action:'archive',expectedVersion:1},store),/saved drafts/);await publishDraft(owner,{pageId,expectedVersion:saved.version});assert.equal(await isPublicMedia(asset.id),true);const pub=(await db.page.findUniqueOrThrow({where:{id:pageId}})).publishedSnapshot;await updateMedia(owner,asset.id,{action:'metadata',expectedVersion:1,alt:'New default'},store);assert.deepEqual((await db.page.findUniqueOrThrow({where:{id:pageId}})).publishedSnapshot,pub);await assert.rejects(updateMedia(owner,asset.id,{action:'archive',expectedVersion:2},store),/published/);const page=await db.page.findUniqueOrThrow({where:{id:pageId}});const rev=await db.pageRevision.findFirstOrThrow({where:{pageId},orderBy:{version:'asc'}});const restored=await restoreDraft(owner,{pageId,revisionId:rev.id,expectedVersion:page.version});await publishDraft(owner,{pageId,expectedVersion:restored.version});assert.equal(await isPublicMedia(asset.id),false);await assert.rejects(updateMedia(owner,asset.id,{action:'archive',expectedVersion:2},store),/published/);});
test('unused archive is recoverable and archived media cannot enter a saved draft',async()=>{const asset=await uploadMedia(owner,bytes,'unused.png',store);await updateMedia(owner,asset.id,{action:'archive',expectedVersion:1},store);assert.ok((await db.mediaAsset.findUniqueOrThrow({where:{id:asset.id}})).archivedAt);const homepage=defaultHomepage() as unknown as Record<string,EditorObject>;homepage.hero.media={mediaId:asset.id,alt:'Alt',decorative:false,focalX:50,focalY:50};const page=await db.page.findUniqueOrThrow({where:{id:pageId}});await assert.rejects(saveDraft(owner,{...original,homepage,pageId,expectedVersion:page.version}),/archived/);await updateMedia(owner,asset.id,{action:'recover',expectedVersion:2},store);assert.equal((await db.mediaAsset.findUniqueOrThrow({where:{id:asset.id}})).archivedAt,null);});
test('storage and audit failures clean files; failed cleanup is durable and retryable',async()=>{const before=await db.mediaAsset.count({where:{creatorId:owner}});const size=files.size;let n=0;const broken={...store,async put(k:string,b:Buffer){await store.put(k,b);if(++n===2)throw new Error('Storage failed')}};await assert.rejects(uploadMedia(owner,bytes,'failure.png',broken),/Storage failed/);assert.equal(files.size,size);assert.equal(await db.mediaAsset.count({where:{creatorId:owner}}),before);n=0;await assert.rejects(uploadMedia(owner,bytes,'cleanup.png',{...broken,async remove(){throw new Error('Offline')}}));const pending=await db.mediaAsset.findFirstOrThrow({where:{creatorId:owner,state:'CLEANUP'}});assert.equal(await isPublicMedia(pending.id),false);await updateMedia(owner,pending.id,{action:'cleanup',expectedVersion:1},store);assert.equal(files.size,size);const constraint='media_fail_'+key.replaceAll('-','');await db.$executeRawUnsafe(`ALTER TABLE "AuditLog" ADD CONSTRAINT "${constraint}" CHECK ("actorId" <> '${owner}' OR action <> 'media.uploaded') NOT VALID`);try{await assert.rejects(uploadMedia(owner,bytes,'audit-failure.png',store));}finally{await db.$executeRawUnsafe(`ALTER TABLE "AuditLog" DROP CONSTRAINT "${constraint}"`);}assert.equal(files.size,size);assert.equal(await db.mediaAsset.count({where:{creatorId:owner}}),before);});
