import {assertTestEnvironment} from '../scripts/test-environment';assertTestEnvironment();
import {test,after} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {db} from '../src/server/db';import {initializeRoofing,saveDraft,restoreDraft} from '../src/server/content';import {defaultRoofing} from '../src/content/roofing-defaults';import {snapshotSchema} from '../src/schemas/content';import {industryDetailSchema} from '../src/schemas/industry-detail';
import {roofingHubFixture} from './fixtures/roofing-hub';
test('Roofing reference contract preserves legacy revisions and forbids duplicate industry links',()=>{
 const v2=roofingHubFixture();assert.equal(v2.schemaVersion,2);assert.equal(industryDetailSchema.parse(defaultRoofing('en','global')).schemaVersion,1);
 const duplicate=structuredClone(v2);duplicate.sections[7].items=[{id:'copy',title:'Roofing',body:'',actionLabel:'',destination:''}];assert.equal(industryDetailSchema.safeParse(duplicate).success,false);
 const missing=structuredClone(v2);delete missing.sections[1].items[0].media;assert.equal(industryDetailSchema.safeParse(missing).success,false);
 const reordered=structuredClone(v2);reordered.sections.reverse();assert.equal(industryDetailSchema.safeParse(reordered).success,false);
});
after(async()=>{await db.$disconnect()});
test('Roofing contract bounds sections, lists, internal destinations and page isolation',()=>{const detail=defaultRoofing('en','global');assert.equal(detail.sections.length,9);assert.equal(detail.sections.find(s=>s.type==='faq')!.items.length,6);assert.ok(!industryDetailSchema.safeParse({...detail,slug:'construction'}).success);const invalid=structuredClone(detail);invalid.sections[2].items[0].destination='https://example.com';assert.ok(!industryDetailSchema.safeParse(invalid).success);const mixed={title:'Roofing',sections:[{id:'x',type:'positioning',heading:'X',body:''}],industryDetail:detail};assert.ok(!snapshotSchema.safeParse(mixed).success);assert.ok(detail.sections.every(s=>s.items.every(i=>i.id)));});
test('Roofing private initialization, stale save, revision restore and audit preserve shared publication',async()=>{
const id='roofing-test-'+randomUUID(),roleId=id+'-role',home=await db.page.findUniqueOrThrow({where:{id:'homepage'}});
await db.role.create({data:{id:roleId,name:roleId,permissions:{create:[{permissionId:'edit_pages'}]}}});await db.user.create({data:{id,email:id+'@example.test',name:'Roofing editor',roles:{create:{roleId}}}});
try{await assert.rejects(()=>initializeRoofing(null),/Unauthorized/);const page=await initializeRoofing(id);assert.equal(page.publishedSnapshot,null);assert.equal((await initializeRoofing(id)).version,page.version);const snapshot=snapshotSchema.parse(page.draftSnapshot);const changed=structuredClone(snapshot);changed.industryDetail!.sections[0].heading='A reviewed roofing heading';const next=await saveDraft(id,{...changed,pageId:'roofing',expectedVersion:page.version});assert.equal(next.version,page.version+1);assert.equal(next.publishedSnapshot,null);await assert.rejects(()=>saveDraft(id,{...changed,pageId:'roofing',expectedVersion:page.version}),/changed/);await assert.rejects(()=>saveDraft(id,{...changed,pageId:'homepage',expectedVersion:home.version}),/match/);const revision=await db.pageRevision.findFirstOrThrow({where:{pageId:'roofing',version:page.version}});const restored=await restoreDraft(id,{pageId:'roofing',revisionId:revision.id,expectedVersion:next.version});assert.deepEqual(restored.draftSnapshot,snapshot);assert.equal(restored.publishedSnapshot,null);assert.ok(await db.auditLog.count({where:{entityId:'roofing',actorId:id,action:'page.draft_saved'}}));const current=await db.page.findUniqueOrThrow({where:{id:'homepage'}});assert.deepEqual(current.draftSnapshot,home.draftSnapshot);assert.deepEqual(current.publishedSnapshot,home.publishedSnapshot);
}finally{await db.pageRevision.deleteMany({where:{pageId:'roofing'}});await db.auditLog.deleteMany({where:{actorId:id}});await db.page.deleteMany({where:{id:'roofing'}});await db.userRole.deleteMany({where:{userId:id}});await db.user.delete({where:{id}});await db.rolePermission.deleteMany({where:{roleId}});await db.role.delete({where:{id:roleId}})}
});
