import {assertTestEnvironment} from '../scripts/test-environment';
assertTestEnvironment();
import {test,expect} from '@playwright/test';
import {randomUUID,randomBytes} from 'node:crypto';
import {hashPassword} from 'better-auth/crypto';
import {mkdirSync} from 'node:fs';
import {db} from '../src/server/db';
import {Prisma} from '../src/generated/prisma/client';
import {selectHomepageCopy} from '../scripts/homepage-pass2-copy.mjs';
const id='correction2-'+randomUUID(),email=id+'@example.test',password=randomBytes(24).toString('base64url');
let original:Awaited<ReturnType<typeof db.page.findUniqueOrThrow>>;
let sections:{id:string;heading:string;body:string}[];
test.beforeAll(async()=>{
 mkdirSync('docs/homepage-correction-2',{recursive:true});
 original=await db.page.findUniqueOrThrow({where:{id:'homepage'}});
 sections=await db.pageSection.findMany({where:{pageId:'homepage'},select:{id:true,heading:true,body:true}});
 await db.user.create({data:{id,name:'Isolated correction reviewer',email,emailVerified:true,roles:{create:{roleId:'administrator'}},accounts:{create:{id:randomUUID(),providerId:'credential',accountId:id,password:await hashPassword(password)}}}});
});
test.afterAll(async()=>{
 if(original)await db.$transaction(async tx=>{
  await tx.page.update({where:{id:'homepage'},data:{title:original.title,draftSnapshot:original.draftSnapshot??Prisma.DbNull,publishedSnapshot:original.publishedSnapshot??Prisma.DbNull,version:original.version,updatedBy:original.updatedBy,updatedAt:original.updatedAt}});
  for(const section of sections)await tx.pageSection.update({where:{id:section.id},data:{heading:section.heading,body:section.body}});
 });
 await db.auditLog.deleteMany({where:{actorId:id}});await db.pageRevision.deleteMany({where:{actorId:id}});await db.user.deleteMany({where:{id}});await db.$disconnect();
});
test('private editorial preview, transparent compact menus, real configured action and deferred form',async({page,browser})=>{
 test.setTimeout(120000);await page.setViewportSize({width:1440,height:1100});
 const login=await page.request.post('/api/auth/sign-in/email',{headers:{Origin:process.env.BETTER_AUTH_URL!},data:{email,password}});expect(login.ok()).toBe(true);
 const {page:before}=await(await page.request.get('/api/cms')).json();
 const selected=selectHomepageCopy(before);
 // A real implemented in-page destination exercises the link without inventing owner routes.
 const destination=selected.homepage.services.items.find((item:{icon:string})=>item.icon==='support').id;
 selected.homepage.flow.items[0].ctaHref='#'+destination;selected.homepage.flow.items[0].ctaLabel='Explore Details';
 const save=await page.request.patch('/api/cms',{headers:{Origin:process.env.BETTER_AUTH_URL!},data:{pageId:before.id,expectedVersion:before.version,...selected}});expect(save.ok()).toBe(true);
 const {page:after,revisions,audit}=await(await page.request.get('/api/cms')).json();
 expect(after.publishedSnapshot).toEqual(before.publishedSnapshot);expect(after.version).toBe(before.version+1);
 expect(revisions.some((row:{version:number})=>row.version===before.version)).toBe(true);
 expect(audit.some((row:{action:string;actorId:string})=>row.action==='page.draft_saved'&&row.actorId===id)).toBe(true);
 const stale=await page.request.patch('/api/cms',{headers:{Origin:process.env.BETTER_AUTH_URL!},data:{pageId:before.id,expectedVersion:before.version,...selected}});expect(stale.status()).toBe(409);
 await page.goto('/preview');await expect(page.locator('#technical-support li')).toHaveCount(5);
 const parent=page.locator('.hp-desktop-nav > .hp-nav-item').filter({has:page.getByRole('link',{name:'Services',exact:true})});
 const panel=parent.locator('.hp-mega-panel'),summary=parent.locator('summary');
 await parent.hover();await expect(summary).toHaveAttribute('aria-expanded','true');
 await expect(parent.locator(':scope > a')).toHaveCSS('background-color','rgba(0, 0, 0, 0)');
 await expect(summary).toHaveCSS('background-color','rgba(0, 0, 0, 0)');
 await expect(parent.locator(':scope > a')).toHaveCSS('box-shadow','none');
 await expect(page.locator('.hp-desktop-nav > .hp-nav-item').first().locator(':scope > a')).toHaveCSS('opacity','0.55');
 expect((await panel.boundingBox())!.width).toBeLessThanOrEqual(920);
 await expect(panel).toHaveCSS('background-color','rgba(255, 255, 255, 0.94)');
 await expect(panel).toHaveCSS('backdrop-filter','blur(32px) saturate(1.2)');
 await expect(page.locator('.hp-header')).toHaveCSS('backdrop-filter','none');
 await panel.getByRole('link',{name:'Web & App Development',exact:true}).hover();
 await expect(summary).toHaveAttribute('aria-expanded','true');
 await expect(panel.getByRole('link',{name:'Web & App Development',exact:true})).toHaveCSS('background-color','rgba(0, 0, 0, 0)');
 await expect(panel.getByRole('link',{name:'eCommerce Solutions',exact:true})).toHaveCSS('opacity','0.55');
 await page.mouse.move(10,900);await expect(summary).toHaveAttribute('aria-expanded','false');
 await summary.focus();await page.keyboard.press('ArrowDown');await expect(panel.getByRole('link').first()).toBeFocused();
 await page.keyboard.press('Escape');await expect(summary).toHaveAttribute('aria-expanded','false');await expect(summary).toBeFocused();
 await page.keyboard.press('Tab');await expect(summary).not.toBeFocused();
 await parent.hover();await page.locator('.hp-hero-copy p').click();await expect(summary).toHaveAttribute('aria-expanded','false');
 await page.locator('#about').scrollIntoViewIfNeeded();await parent.hover();await expect(page.locator('.hp-header')).toHaveClass(/is-scrolled/);await expect(panel).toHaveCSS('background-color','rgba(255, 255, 255, 0.94)');
 await page.mouse.move(10,900);await page.waitForTimeout(300);
 const flow=page.locator('#technical-support'),action=flow.getByRole('link',{name:'Explore Details'}),circle=action.locator('.hp-flow-action-circle');
 await flow.scrollIntoViewIfNeeded();await action.scrollIntoViewIfNeeded();
 await expect(action).toHaveAttribute('href','#'+destination);await expect(action.locator('a,button')).toHaveCount(0);
 await expect(circle).toHaveCSS('background-color','rgba(0, 0, 0, 0)');
 await action.screenshot({path:'docs/homepage-correction-2/action-default-isolated.png'});
 const box=(await circle.boundingBox())!;await page.mouse.move(box.x+box.width-8,box.y+box.height/2);await page.waitForTimeout(500);
 await expect(circle).toHaveCSS('background-color','rgb(25, 30, 50)');
 const offset=await circle.evaluate(el=>parseFloat((el as HTMLElement).style.getPropertyValue('--plus-x')));expect(offset).toBeGreaterThan(0);expect(offset).toBeLessThanOrEqual(3);
 await action.screenshot({path:'docs/homepage-correction-2/action-hover-isolated.png'});
 await action.click();await expect(page).toHaveURL(new RegExp('#'+destination+'$'));await expect(page.locator('#'+destination)).toBeInViewport();
 await page.keyboard.press('Tab');await action.focus();await expect(action).toHaveCSS('outline-style','solid');
 await page.emulateMedia({reducedMotion:'reduce'});await action.hover();await expect(circle.locator('span')).toHaveCSS('transform','none');
 const footer=page.locator('#contact');await footer.scrollIntoViewIfNeeded();
 const input=page.getByLabel('Enter your email address'),submit=page.getByRole('button',{name:'Submit email address'});
 await input.fill('invalid');await submit.click();expect(await input.evaluate((el:HTMLInputElement)=>el.validity.typeMismatch)).toBe(true);
 let submissions=0;page.on('request',request=>{if(request.method()==='POST'||request.url().includes('email='))submissions++;});
 await input.fill('preview@example.test');await submit.click();await expect(page.locator('#footer-email-status')).toContainText('has not been sent or saved');expect(submissions).toBe(0);
 const noJs=await browser.newContext({javaScriptEnabled:false,storageState:await page.context().storageState()});
 const fallback=await noJs.newPage();await fallback.goto(process.env.BETTER_AUTH_URL+'/preview');
 await expect(fallback.getByLabel('Enter your email address')).toBeDisabled();await expect(fallback.getByRole('button',{name:'Submit email address'})).toBeDisabled();await noJs.close();
 const touch=await browser.newContext({isMobile:true,hasTouch:true,viewport:{width:390,height:844},storageState:await page.context().storageState()});
 const touchPage=await touch.newPage();await touchPage.goto(process.env.BETTER_AUTH_URL+'/preview');
 const touchAction=touchPage.locator('#technical-support .hp-flow-action');await touchAction.dispatchEvent('pointermove',{clientX:40,clientY:40,pointerType:'touch'});
 expect(await touchAction.locator('.hp-flow-action-circle').evaluate(el=>(el as HTMLElement).style.getPropertyValue('--plus-x'))).toBe('');await touch.close();
 for(const width of [1440,768,390]){await page.setViewportSize({width,height:1100});await footer.scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(input).toBeVisible();await flow.scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
});
