import {assertTestEnvironment} from '../scripts/test-environment';assertTestEnvironment();
import {test,expect} from '@playwright/test';import {randomUUID,randomBytes} from 'node:crypto';import {hashPassword} from 'better-auth/crypto';import sharp from 'sharp';import {mkdirSync} from 'node:fs';import {db} from '../src/server/db';import {Prisma} from '../src/generated/prisma/client';import {mediaStorage} from '../src/server/media-storage';
const id='media-browser-'+randomUUID(),email=id+'@example.test',password=randomBytes(24).toString('base64url');let original:Awaited<ReturnType<typeof db.page.findUniqueOrThrow>>;let sections:{id:string;heading:string;body:string}[];let bytes:Buffer;
test.beforeAll(async()=>{mkdirSync('docs/homepage-media-review',{recursive:true});await db.rateLimit.deleteMany();original=await db.page.findUniqueOrThrow({where:{id:'homepage'}});sections=await db.pageSection.findMany({where:{pageId:'homepage'},select:{id:true,heading:true,body:true}});bytes=await sharp({create:{width:1000,height:700,channels:3,background:'#10aabc'}}).png().toBuffer();await db.user.create({data:{id,name:'Isolated media reviewer',email,emailVerified:true,roles:{create:{roleId:'administrator'}},accounts:{create:{id:randomUUID(),providerId:'credential',accountId:id,password:await hashPassword(password)}}}});});
test.afterAll(async()=>{if(original)await db.$transaction(async tx=>{await tx.page.update({where:{id:'homepage'},data:{title:original.title,status:original.status,draftSnapshot:original.draftSnapshot??Prisma.DbNull,publishedSnapshot:original.publishedSnapshot??Prisma.DbNull,publishedAt:original.publishedAt,version:original.version,updatedBy:original.updatedBy,updatedAt:original.updatedAt}});for(const s of sections)await tx.pageSection.update({where:{id:s.id},data:{heading:s.heading,body:s.body}});});await db.auditLog.deleteMany({where:{actorId:id}});await db.pageRevision.deleteMany({where:{actorId:id}});await db.pagePublication.deleteMany({where:{actorId:id}});const assets=await db.mediaAsset.findMany({where:{creatorId:id}});for(const a of assets)for(const v of Object.values(a.variants as Record<string,{key:string}>))await mediaStorage.remove(v.key);await db.mediaAsset.deleteMany({where:{creatorId:id}});await db.mediaUploadQuota.deleteMany({where:{actorId:id}});await db.user.deleteMany({where:{id}});await db.$disconnect();});
test('secure private uploads, library recovery, draft preview and publication readiness walkthrough',async({browser,request})=>{test.setTimeout(90000);const origin=process.env.BETTER_AUTH_URL!;expect((await request.post('/api/media',{headers:{Origin:origin,'Content-Type':'application/octet-stream'},data:bytes})).status()).toBe(401);const context=await browser.newContext({baseURL:origin,viewport:{width:1440,height:1000},recordVideo:{dir:'docs/homepage-media-review/raw',size:{width:1440,height:1000}}});const page=await context.newPage();try{
 await page.goto('/login');await page.getByLabel('Email address').fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('navigation',{name:'Homepage sections'})).toBeVisible();
 const before=await(await request.get('/api/public-page')).json();const shot=async(name:string)=>{await page.waitForTimeout(1200);await page.screenshot({path:'docs/homepage-media-review/'+name+'.png'});};
 for(const invalidOrigin of [undefined,'https://invalid.example'])expect((await page.request.post('/api/media',{headers:{...(invalidOrigin?{Origin:invalidOrigin}:{}),'Content-Type':'application/octet-stream'},data:bytes})).status()).toBe(403);
 for(const invalid of [Buffer.from('<svg><script>alert(1)</script></svg>'),Buffer.from('MZ executable'),Buffer.concat([bytes,Buffer.from('<?php exit;')])])expect((await page.request.post('/api/media',{headers:{Origin:origin,'Content-Type':'application/octet-stream','X-File-Name':'unsafe.png'},data:invalid})).status()).toBe(415);
 await page.getByRole('navigation',{name:'Homepage sections'}).getByRole('button',{name:/Hero/}).click();await page.getByLabel('Heading prefix',{exact:true}).fill('Private upload review');await page.getByRole('button',{name:'Choose image',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Media library'});await expect(dialog.getByLabel('Upload raster image')).toBeVisible();let releaseInspection!:()=>void;const inspectionGate=new Promise<void>(resolve=>{releaseInspection=resolve;});let delayInspection=true;await page.route(/\/api\/media\/media_[0-9a-f-]+$/,async route=>{if(route.request().method()!=='GET'||!delayInspection){await route.continue();return;}delayInspection=false;const response=await route.fetch();await inspectionGate;await route.fulfill({response});});await dialog.getByLabel('Upload raster image').setInputFiles({name:'review-photo.png',mimeType:'image/png',buffer:bytes});await expect(dialog.getByText('Image uploaded privately.',{exact:false})).toBeVisible();try{await expect(dialog.getByLabel('Default alt text',{exact:true})).toBeDisabled();await expect(dialog.getByLabel('Default focal horizontal')).toBeDisabled();await expect(dialog.getByRole('button',{name:'Save image defaults',exact:true})).toBeDisabled();await expect(dialog.getByRole('button',{name:'Use image',exact:true})).toBeDisabled();}finally{releaseInspection();}await expect(dialog.getByLabel('Default alt text',{exact:true})).toBeEnabled();await dialog.getByLabel('Default alt text',{exact:true}).fill('Isolated turquoise image');await dialog.getByLabel('Default focal horizontal').fill('35');await dialog.getByRole('button',{name:'Save image defaults',exact:true}).click();await expect(dialog.getByText('Image defaults saved.',{exact:false})).toBeVisible();await shot('upload-details');
 page.once('dialog',d=>d.accept());await dialog.getByRole('button',{name:'Archive image',exact:true}).click();await expect(dialog.getByRole('button',{name:'Recover image'})).toBeVisible();await dialog.getByRole('button',{name:'Recover image'}).click();await expect(dialog.getByRole('button',{name:'Use image'})).toBeEnabled();await dialog.getByRole('button',{name:'Use image'}).click();await expect(page.getByLabel('Heading prefix',{exact:true})).toHaveValue('Private upload review');await expect(page.getByLabel('Image alt text',{exact:true})).toHaveValue('Isolated turquoise image');await page.getByRole('button',{name:'Save draft',exact:true}).click();await expect(page.getByRole('status')).toContainText('Draft saved');await expect(page.getByRole('button',{name:'Publish',exact:true})).toBeEnabled();
 const data=await(await page.request.get('/api/cms')).json(),mediaId=data.page.homepage.hero.media.mediaId;expect((await request.get('/api/media/'+mediaId+'/large')).status()).toBe(401);expect((await page.request.get('/api/media/'+mediaId+'/large')).headers()['content-type']).toBe('image/webp');expect(await(await request.get('/api/public-page')).json()).toEqual(before);
 await page.getByRole('button',{name:'Preview',exact:true}).click();const frame=page.frameLocator('iframe');await expect(frame.locator('h1')).toContainText('Private upload review');await expect(frame.locator('.hp-hero-art img')).toHaveAttribute('src',new RegExp(mediaId));await expect(frame.locator('.hp-hero-art img')).toHaveAttribute('srcset',/640w/);await shot('private-preview');await page.getByRole('button',{name:'Mobile',exact:true}).click();await shot('mobile-preview');await page.getByRole('button',{name:'Close preview',exact:true}).click();await page.getByRole('button',{name:'Choose image',exact:true}).click();await dialog.getByLabel('Find image').fill('review-photo');await dialog.getByRole('button',{name:/review-photo.png/}).click();await expect(dialog.getByRole('button',{name:'Archive image',exact:true})).toBeDisabled();await expect(dialog.getByText('Saved drafts:',{exact:false})).toContainText('CODEYEA');await shot('usage-protection');await dialog.getByRole('button',{name:'Close media library'}).click();
 await page.getByRole('button',{name:'Revisions',exact:true}).click();await page.getByRole('button',{name:/Preview version/}).first().click();await expect(page.locator('.comparison-table')).toContainText('Heading prefix');await shot('readable-revisions');
 await db.userRole.deleteMany({where:{userId:id}});await db.userRole.create({data:{userId:id,roleId:'editor'}});expect((await page.request.post('/api/media',{headers:{Origin:origin,'Content-Type':'application/octet-stream'},data:bytes})).status()).toBe(403);expect((await page.request.patch('/api/media/'+mediaId,{headers:{Origin:origin},data:{action:'metadata',expectedVersion:4,alt:'Forbidden'}})).status()).toBe(403);
 }finally{await context.close();await page.video()?.saveAs('docs/homepage-media-review/walkthrough.webm');}});
