import {assertTestEnvironment} from '../scripts/test-environment';
assertTestEnvironment();
import {test,expect} from '@playwright/test';
test('mobile refinement layout, touch, keyboard and review recording',async({browser,baseURL})=>{
 test.setTimeout(120000);
 const context=await browser.newContext({baseURL,viewport:{width:390,height:844},hasTouch:true,isMobile:true,recordVideo:{dir:'docs/recordings/raw',size:{width:390,height:844}}});
 const page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.waitForTimeout(600);
 const menu=page.locator('.hp-mobile-trigger');await menu.click();const panel=page.getByRole('dialog',{name:'CODEYEA navigation'});await expect(panel).toBeVisible();await expect(page.locator('body')).toHaveCSS('overflow','hidden');await expect(page.getByRole('button',{name:'Close navigation'})).toBeFocused();
 await page.keyboard.press('Shift+Tab');await expect(panel.getByRole('link',{name:'Request Service',exact:true})).toBeFocused();await page.keyboard.press('Tab');await expect(page.getByRole('button',{name:'Close navigation'})).toBeFocused();
 await panel.locator('summary').first().click();await expect(panel.getByRole('link',{name:'Web & App Development',exact:true})).toBeVisible();await page.waitForTimeout(500);await page.keyboard.press('Escape');await expect(panel).not.toBeVisible();await expect(menu).toBeFocused();await expect(page.locator('body')).not.toHaveCSS('overflow','hidden');
 await menu.click();await panel.getByRole('link',{name:'Explore Services',exact:true}).click();await expect(panel).not.toBeVisible();await page.waitForTimeout(650);
 await expect(page.getByRole('button',{name:/pause words|resume words/i})).toHaveCount(0);await expect(page.locator('.hp-wave')).toHaveCount(0);await expect(page.locator('#services article').first().locator('.hp-service-link')).toHaveCSS('opacity','1');
 const cdp=await context.newCDPSession(page);
 async function swipe(selector:string){const view=page.locator(selector);await view.scrollIntoViewIfNeeded();const r=(await view.boundingBox())!;const y=Math.min(650,Math.max(180,r.y+Math.min(r.height/2,220)));const x=r.x+Math.min(r.width,370)*.85;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=12;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-i*20,y}]});await page.waitForTimeout(20);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(650);}
 await page.locator('#hosting').scrollIntoViewIfNeeded();await page.getByRole('button',{name:'Annually',exact:true}).click();await expect(page.locator('.hp-mobile-price').first()).toContainText('$135');await page.getByRole('button',{name:'Monthly',exact:true}).click();await swipe('.hp-mobile-hosting-viewport');await expect(page.getByRole('button',{name:'Show Colossal plan'})).toHaveAttribute('aria-current','true');await page.getByRole('button',{name:'Show Superb plan'}).click();await page.locator('.hp-mobile-plan summary').first().click();await page.waitForTimeout(500);await page.locator('.hp-mobile-plan summary').first().click();
 await page.locator('#work').scrollIntoViewIfNeeded();await swipe('.hp-carousel--project .hp-carousel-viewport');await expect(page.locator('.hp-carousel--project')).toHaveClass(/is-expanded/);await expect.poll(()=>page.locator('.hp-project-intro-shell').evaluate(e=>e.getBoundingClientRect().height)).toBeLessThan(2);await page.getByRole('button',{name:'Previous Project previews slide',exact:true}).click();await expect(page.locator('.hp-carousel--project')).not.toHaveClass(/is-expanded/);await page.getByRole('button',{name:'Branding',exact:true}).click();await page.getByRole('button',{name:'All',exact:true}).click();
 await page.locator('#industries').scrollIntoViewIfNeeded();await page.getByRole('button',{name:'Pause Industries autoplay'}).click();await swipe('.hp-carousel--industry .hp-carousel-viewport');await expect(page.locator('.hp-carousel--industry .hp-carousel-count')).toContainText('02');await page.locator('#contact').scrollIntoViewIfNeeded();await page.waitForTimeout(900);
 for(const size of [{width:320,height:844},{width:375,height:844},{width:390,height:844},{width:768,height:1024},{width:812,height:375}]){await page.setViewportSize(size);await page.waitForTimeout(200);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();expect(await page.locator('#services').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length)).toBe(2);await expect(page.locator('.hp-flow')).not.toHaveClass(/is-enhanced/);}
 await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#services').scrollIntoViewIfNeeded();await expect(page.locator('.hp-service-word').first()).toHaveCSS('animation-name','none');await expect(page.locator('[data-count-to]')).toHaveText('18');await expect(page.locator('.hp-media-cursor').first()).toHaveCSS('display','none');
 // Visit every section before a full-page capture so once-only entrances have completed.
 for(const id of ['#about','.hp-experience','#service-flow','#hosting','#work','#industries','#contact'])await page.locator(id).scrollIntoViewIfNeeded();await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(400);await page.screenshot({path:'docs/screenshots/homepage-mobile-refinement-390.png',fullPage:true});expect(errors).toEqual([]);const video=page.video();await context.close();await video?.saveAs('docs/recordings/homepage-mobile-refinement-390.webm');
});

test('service words stagger without layout shifts on desktop and enter once on touch',async({browser,baseURL})=>{
 const desktop=await browser.newContext({baseURL,viewport:{width:1440,height:900}});const page=await desktop.newPage();await page.goto('/');const card=page.locator('#services article').first();await card.scrollIntoViewIfNeeded();await page.mouse.move(0,0);await page.waitForTimeout(500);const initial=(await card.boundingBox())!;const word=card.locator('.hp-service-word').first();await card.hover();await expect(word).toHaveCSS('transform','matrix(1, 0, 0, 1, 0, -7)');await expect(card.locator('.hp-service-link')).toHaveCSS('opacity','1');expect((await card.boundingBox())!.height).toBeCloseTo(initial.height,2);await page.mouse.move(0,0);await expect(word).toHaveCSS('transform','none');await card.locator('.hp-service-link').focus();await expect(word).toHaveCSS('transform','matrix(1, 0, 0, 1, 0, -7)');await desktop.close();
 const touch=await browser.newContext({baseURL,viewport:{width:390,height:844},isMobile:true,hasTouch:true});const mobile=await touch.newPage();await mobile.goto('/');await mobile.locator('#services article').first().scrollIntoViewIfNeeded();await expect(mobile.locator('#services article').first()).toHaveClass(/is-inview/);await expect(mobile.locator('.hp-service-word').first()).toHaveCSS('animation-name','hp-word-rise');await expect(mobile.locator('.hp-service-link').first()).toHaveCSS('opacity','1');await touch.close();
});
