import {accordionFixtures,flowFixtures,hostingFixtures,industryFixtures,serviceFixtures} from './homepage-review';
import {homepageEditorSchema,type EditorObject} from '../schemas/homepage-editor';
const contact='https://codeyea.com/contact/';
export const iconKeys=['development','commerce','automation','hosting','growth','creative','support','strategy'];
export function defaultHomepage(localeId='en',marketId='global'){
 const item=(id:string,position:number,value:EditorObject):EditorObject=>({id,localeId,marketId,position,enabled:true,...value});
 const image=(mediaId:string,alt='',decorative=true):EditorObject=>({mediaId,alt,decorative,focalX:50,focalY:50});
 const words=(values:string[])=>values.map((title,i)=>item('word-'+i,i,{title}));
 const cta=(ctaLabel:string,ctaHref=contact)=>({ctaLabel,ctaHref});
 const nav=[['About Us','#about'],['Services','#services'],['Hosting','#hosting'],['Industries','#industries'],['Work','#work']].map(([title,href],i)=>item('nav-'+i,i,{title,href,parentId:''}));
 serviceFixtures.forEach((s,i)=>nav.push(item('nav-service-'+i,10+i,{title:s.title,href:'#'+s.id,parentId:'nav-1'})));
 industryFixtures.forEach((s,i)=>nav.push(item('nav-industry-'+i,20+i,{title:s.title,href:'#industry-list',parentId:'nav-3'})));
 const labels=['NVMe SSD Storage','Premium Bandwidth','Sub Domains','SSL Certificate','cPGuard Protection','One Click App Installer','Mail Accounts','Uptime','Malware scanner','DDoS protection','Weekly Backup'];
 const features=labels.map((title,i)=>item('feature-'+i,i,{title}));
 const data={schemaVersion:1,localeId,marketId,seo:{title:'Website Design, SEO & Digital Services | CODEYEA',description:'CODEYEA builds websites, apps, e-commerce experiences and digital growth systems for businesses worldwide.'},
 header:{items:nav,actions:[['Submit a Ticket','https://hosting.codeyea.com/submitticket.php'],['Client Area','https://hosting.codeyea.com/login'],['Request Service',contact]].map(([title,href],i)=>item('mobile-action-'+i,i,{title,href}))},
 hero:{prefix:'We build e-commerce solutions tailored to your',suffix:'',words:words(['grocer.','boutique.','coffee shop.','tech market.']),body:'We help you to increase your sales.',...cta('Let’s talk — Send a message','#contact'),media:image('hero')},
 logos:{items:Array.from({length:6},(_,i)=>item('client-'+(i+1),i,{title:'Existing site mark '+(i+1),media:image('client-'+(i+1),'Existing site mark '+(i+1)+'; relationship awaiting confirmation',false),href:''}))},
 services:{items:serviceFixtures.map((s,i)=>item(s.id,i,{title:s.title,body:s.body,icon:iconKeys[i],...cta('Learn More')}))},
 about:{eyebrow:'CODEYEA is different. Who we are.',heading:'Where Creativity Meets Innovation — Digital Solutions With Purpose.',body:'CODEYEA is a digital innovation agency focused on helping businesses build stronger digital foundations. We bring web development, eCommerce, AI automation, hosting, SEO, branding and technical support together around what your business needs.',media:image('about','Collaborative design planning around a table',false),items:accordionFixtures.map((s,i)=>item(s.id,i,{title:s.title,body:s.body})),...cta('Explore our approach','#service-flow')},
 experience:{heading:'Experience makes the difference.',body:'Ideas, design and technology, brought together with care.',value:18,unit:'Years of experience',approved:false,media:image('team'),...cta('Explore our work','#work')},
 flow:{items:flowFixtures.map((s,i)=>item(s.id,i,{title:s.title,body:s.body,media:image(['support','branding','ecommerce'][i]),ctaLabel:'',ctaHref:''}))},
 hosting:{heading:'CODEYEA Hosting for every website.',body:'Compare the reference packages below. Product availability, inclusions and pricing need confirmation.',monthlyLabel:'Monthly',annualLabel:'Annually',features,plans:hostingFixtures.map((p,i)=>item('plan-'+p.title.toLowerCase(),i,{title:p.title,monthlyPrice:p.price,annualPrice:['$135','$201','TBC'][i],monthlyUnit:'/mo',annualUnit:i===2?'TBC':'/year',description:p.storage+' NVMe SSD storage',renewal:'Reference pricing · renewal and inclusions TBC',featured:i===1,values:features.map((f,j)=>item('value-'+i+'-'+j,j,{featureId:String(f.id),value:j===0?p.storage:j===1?p.bandwidth:j===2?p.domains:j===6?'Unlimited':j===7?'99.9%*':'✓'})),...cta('Get Started')}))},
 projects:{heading:'Selected Case Studies',eyebrow:'Latest projects',...cta('See More','#project-list'),items:[['mobile','Mobile interface','Web & App','Existing site imagery; project details awaiting approval.'],['web','Website experience','Web & App',''],['brand','Product campaign','Branding','Reference artwork; client attribution unverified.']].map(([id,title,categories,body],i)=>item(id,i,{title,categories,body,media:image('project-'+id),href:'',featured:i===0}))},
 industries:{heading:'Industries',body:'Digital experiences shaped around your field, your customers and the way you work.',...cta('Explore Industries','#industry-list'),items:industryFixtures.map((s,i)=>item(s.id,i,{title:s.title,eyebrow:'Industries',body:'Digital experiences shaped around your field, your customers and the way you work.',media:image(['healthcare','construction','real-estate','commerce','legal','oil-gas','roofing','small-business'][i]),href:''}))},
 footer:{heading:'Let’s',suffix:'what’s next.',words:words(['create','develop','grow']),supportHeading:'Have a project in mind?',body:'Let’s start a conversation.',...cta('Start a conversation'),contact:'Digital Innovation Agency',copyright:'© 2026 CODEYEA',groups:[item('footer-explore',0,{title:'Explore',links:nav.filter(n=>!n.parentId).map((n,i)=>item('footer-nav-'+i,i,{title:n.title,href:n.href}))}),item('footer-connect',1,{title:'Connect',links:[item('footer-contact',0,{title:'Contact us',href:contact}),item('footer-support',1,{title:'Technical support',href:'https://hosting.codeyea.com/submitticket.php'})]}),item('footer-portal',2,{title:'Client area',links:[item('footer-client',0,{title:'Client portal',href:'https://hosting.codeyea.com/login'}),item('footer-cms',1,{title:'Open content studio',href:'/admin'})]})]}
 };return homepageEditorSchema.parse(data);
}
export function resolveHomepage(value:unknown,localeId='en',marketId='global'){return (value?homepageEditorSchema.parse(value):defaultHomepage(localeId,marketId)) as unknown as Record<string,EditorObject>;}

