import {industryDetailSchema,type DetailSection} from '../schemas/industry-detail';
const media={mediaId:'roofing',alt:'A person on the metal roof of a timber house',decorative:false,focalX:50,focalY:50,tabletFocalX:50,tabletFocalY:50,mobileFocalX:50,mobileFocalY:50};
const item=(id:string,title:string,body:string,actionLabel='',destination='')=>({id,title,body,actionLabel,destination});
const section=(type:DetailSection['type'],label:string,heading:string,body:string,items:ReturnType<typeof item>[]=[],extra:Partial<DetailSection>={})=>({id:'roofing-'+type,type,enabled:true,label,heading,body,items,temporaryMedia:true,actionLabel:'',destination:'',...extra});
export function defaultRoofing(localeId:string,marketId:string,contact='#contact'){
return industryDetailSchema.parse({schemaVersion:1,slug:'roofing',localeId,marketId,hero:{title:'Roofing',media,temporaryMedia:true},sections:[
section('overview','ROOFING INDUSTRY OVERVIEW','A stronger first impression, before the first estimate.',
'Roofing customers rarely choose a contractor from a name alone. They look for the service they need, evidence of completed work and a clear sense of who will be visiting their property. Some are planning a replacement; others are trying to understand a leak or arrange a repair. Your digital presence should help each person find relevant information and take a sensible next step.\n\nA useful roofing website explains the work you actually undertake, the areas you genuinely serve and how an estimate request is handled. Clear service pages, real project photographs and accurate business information help people evaluate your business alongside recommendations and reviews. Credentials, insurance and warranty information should be shown only where you can verify them.\n\nCODEYEA connects website design, local search, content and inquiry handling around that customer journey. The aim is to make your capabilities easier to understand and give your team better context for the first conversation—not to promise a particular number of leads or jobs.'),
section('needs','WHAT ROOFING BUSINESSES NEED','Make it easier to choose you with confidence.',
'Your website needs to answer practical questions while helping your team manage the next step. We organize the experience around the information a property owner needs before requesting an estimate.',[
item('roofing-need-clarity','Clear services and coverage','Separate repairs, replacements and other services you actually offer. Explain who each service is for and identify your real service area so customers can assess the fit before getting in touch.'),
item('roofing-need-trust','Evidence people can evaluate','Use your own project photographs and useful descriptions of the work. Present verified credentials and genuine reviews with context, rather than relying on broad claims about quality.'),
item('roofing-need-inquiries','A practical inquiry path','Offer an estimate request that works on a phone and collects useful property and job details. Make contact options clear and explain what information helps your team respond.')],{media}),
section('services','DIGITAL SERVICES FOR ROOFING COMPANIES','The right digital tools for the work you do.',
'Choose the work around your current priorities: a clearer website, more useful visibility, stronger project presentation or a better way to handle incoming inquiries. These services can work together without requiring every roofing business to adopt the same setup.',[
item('roofing-service-web','Roofing websites and service pages','Build a responsive website around the roofing services you deliver. Clear navigation, readable service information and straightforward estimate forms help property owners understand the offer and contact the right team. Existing websites can also be reviewed and improved rather than automatically replaced.','Explore Web & App Development'),
item('roofing-service-search','Local SEO and business profiles','Organize service and location information around the areas you genuinely cover. We can improve page structure, business details and your Google Business profile so searchers encounter consistent, relevant information. Search visibility is ongoing work; rankings and lead volumes are never guaranteed.','Explore SEO & Digital Growth'),
item('roofing-service-projects','Project galleries and trust content','Present real roofing work through before-and-after photographs, material details and concise project explanations. We help structure owner-supplied reviews, credentials and warranty information where appropriate, so visitors can judge your work from evidence rather than unsupported marketing claims.','Explore Branding & Creative'),
item('roofing-service-campaigns','Focused campaigns and landing pages','Connect paid search or content campaigns to a specific roofing service and a relevant landing page. Clear messaging, defined service areas and inquiry measurement help you assess the quality of the response. Campaign scope and spending are agreed around the business rather than assumed.','Explore Digital Strategy'),
item('roofing-service-workflow','Estimate requests and connected workflows','Collect the details your team needs, such as the type of work, property location and preferred contact method. Where suitable, connect website inquiries with existing business tools to reduce re-entry and make follow-up easier to track. Technical scope is confirmed around your current systems.','Explore AI & Workflow Automation'),
item('roofing-service-support','Hosting, maintenance and technical support','Keep service information, project galleries and contact paths manageable after launch. We can support hosting, updates and technical troubleshooting, with responsibilities agreed for your site. A maintainable setup makes routine improvements easier as the services, team or business processes change.','Explore Hosting & Support')]),
section('growth','ROOFING GROWTH SYSTEM','Connect discovery to the next conversation.',
'Each stage gives the next one a stronger foundation. The system is about helping the right customer understand your business and helping your team handle the opportunity well.',[
item('roofing-growth-attract','Attract','Help people looking for your actual roofing services discover relevant pages through local search, useful content and appropriately scoped campaigns. Keep service-area information accurate.'),
item('roofing-growth-trust','Build Trust','Show real work, explain your process and make verified business information easy to find. Answer the questions customers use to compare contractors before they contact you.'),
item('roofing-growth-convert','Convert','Give visitors a clear estimate-request path that works on mobile. Collect enough job context to support a useful conversation without turning the form into an obstacle.'),
item('roofing-growth-grow','Grow','Review how inquiries arrive and where the experience creates friction. Improve pages, follow-up and project content as you learn, using business feedback alongside website data.')]),
section('process','HOW WE WORK','A clear process, built around your roofing business.',
'We agree what needs to improve before choosing the tools. Each stage gives you an opportunity to review the direction and confirm the details that customers will see.',[
item('roofing-process-discovery','Discovery','Understand your services, customer questions, service area, existing website and inquiry process. Identify the project photos, credentials and business information that you can provide.'),
item('roofing-process-strategy','Strategy','Define the page structure, content priorities and paths to an estimate request. Agree the services, integrations and measures that belong in the project scope.'),
item('roofing-process-build','Design & Build','Develop the content and responsive experience together. Review service pages, galleries, forms and connections with your team before preparing the site for release.'),
item('roofing-process-launch','Launch & Growth','Check links, forms, mobile layouts and the agreed measurement setup. Prepare the handover and plan ongoing improvements around how the website is actually used.')]),
section('outcomes','BUSINESS OUTCOMES','A more useful digital foundation for your roofing work.',
'The value of a roofing website is in how well it supports the business and its customers. These are practical objectives for the work, not promises of a particular commercial result.',[
item('roofing-outcome-understanding','Better-informed customers','Clear services, coverage and project information help people understand whether your business suits their job before requesting an estimate.'),
item('roofing-outcome-context','More useful inquiry context','A considered contact path helps your team start with relevant details and identify what needs to be discussed next.'),
item('roofing-outcome-manage','Easier ongoing improvement','An organized, maintainable website makes it simpler to add completed work, update service information and improve the customer journey over time.')]),
section('faq','ROOFING FAQ','Questions worth answering before we begin.','',[
item('roofing-faq-website','Why does a roofing company need more than a basic website?','Customers need to understand the services you offer, see evidence of your work and know how to request help. A useful website brings that information together in a form that is easy to navigate on a phone. It also gives referrals a reliable place to learn more about your business.'),
item('roofing-faq-leads','How can digital work support roofing inquiries?','Local SEO, relevant service content and appropriately scoped campaigns can help customers find you. Clear estimate forms and contact options then help them take the next step. We consider the full journey and agree what to measure; we do not guarantee rankings, inquiry volumes or booked work.'),
item('roofing-faq-photos','Can the website include before-and-after roofing photographs?','Yes. Project galleries can show your own completed work, with descriptions of the service, materials or problem addressed. You provide photographs you have permission to use and confirm the project details. Temporary design imagery is replaced before it is presented as evidence of your work.'),
item('roofing-faq-profile','Can you help with our Google Business profile and service areas?','We can review the profile and website together so contact details, service information and coverage are consistent. Location content should reflect areas you actually serve. Recommendations depend on your current setup and business eligibility; no location or office presence is invented.'),
item('roofing-faq-existing','Do we need to replace our existing roofing website?','Not necessarily. We first review the structure, mobile experience, content and inquiry path. Some businesses need targeted improvements; others need a rebuild to address deeper limitations. The recommendation should reflect what can be maintained and improved sensibly.'),
item('roofing-faq-tools','Can estimate requests connect to our existing tools?','Where an appropriate integration is available, inquiries can connect with your existing customer or project-management tools. We review the available access, data fields and workflow before confirming the scope. Human follow-up and clear ownership remain part of the process.')]),
section('related','RELATED EXPERTISE','Explore the work behind your next step.',
'A roofing project can draw on several areas of digital expertise. Explore the services behind a useful website and the industries that share similar needs for clear information, project evidence and practical customer communication.',[
item('roofing-related-web','Web & App Development','Related service','Explore Web & App Development'),item('roofing-related-seo','SEO & Digital Growth','Related service','Explore SEO & Digital Growth'),item('roofing-related-auto','AI & Workflow Automation','Related service','Explore AI & Workflow Automation'),item('roofing-related-construction','Construction','Related industry','Explore Construction'),item('roofing-related-property','Real Estate','Related industry','Explore Real Estate'),item('roofing-related-small','Small Business','Related industry','Explore Small Business')]),
section('cta','LET’S WORK TOGETHER','Let’s make your roofing business easier to find and understand.',
'Tell us about your services, your current website and how estimate requests reach your team. We can help identify the next practical improvement and define a digital approach around the way your roofing business works.',[],{actionLabel:'Start a Conversation',destination:contact})]});
}
