import {servicesPageSchema,type ServiceItem,type ServiceSection} from '../schemas/services-page';
import type {AboutMedia} from '../schemas/about';
import {servicePageDestination} from './service-destinations';

export function defaultServices(localeId:string,marketId:string,media:AboutMedia,cardMedia:AboutMedia[]=[],contact='https://codeyea.com/contact/'){
 const item=(id:string,title:string,body:string,label='',list:string[]=[]):ServiceItem=>({id,title,body,label,list:list.map((text,n)=>({id:`${id}-line-${n+1}`,text})),destination:null,actionLabel:''});
 const section=(id:ServiceSection['id'],label:string,heading:string,body:string,items:ServiceItem[]=[]):ServiceSection=>({id,label,heading,body,items,outcomes:[],closing:'',actionLabel:'',destination:null});
 const intro=section('services-intro','SERVICES','Smarter digital services built to move businesses forward.','CODEYEA combines artificial intelligence, strategy, design, development, SEO, GEO and digital marketing to create connected solutions shaped around real business goals.\n\nFrom improving visibility and customer experience to automating operations and building custom digital platforms, every service is planned as part of a system that can support long-term growth.',[
  item('sv-cap-ai','Artificial Intelligence & Automation','Practical AI agents, assistants and automated workflows designed around the company’s information, processes and customer needs.'),
  item('sv-cap-growth','Visibility & Growth','SEO, GEO and digital marketing strategies that help businesses become easier to discover across search engines, AI-powered answers and relevant digital channels.'),
  item('sv-cap-products','Digital Products & Commerce','Websites, applications and e-commerce platforms designed to support customers, operations and future growth.'),
  item('sv-cap-brand','Brand & Experience','Brand identity, interface design and visual communication that create consistency, recognition and trust.')]);
 intro.outcomes=[item('sv-outcome-operations','Smarter Operations','Use AI, automation and connected workflows to reduce repetitive work and improve access to business information.'),item('sv-outcome-visibility','Greater Visibility','Strengthen discovery through SEO, Generative Engine Optimization and coordinated digital marketing.'),item('sv-outcome-experiences','Better Experiences','Create responsive, clear and user-friendly experiences across websites, stores and applications.'),item('sv-outcome-growth','Sustainable Growth','Connect strategy, technology, design and measurement to support long-term business development.')];
 const priority=section('services-priority','PRIORITY SERVICES','Connected capabilities. Practical possibilities.','',[
 item('sv-priority-ai','AI Solutions & Business Automation','AI agents, intelligent assistants and automated workflows that help businesses improve operations, organize information and respond faster.'),
 item('sv-priority-seo','SEO & GEO','Search Engine Optimization and Generative Engine Optimization that improve how businesses are discovered across traditional search and AI-powered platforms.'),
 item('sv-priority-development','Web & App Development','Custom websites, web applications, mobile applications and AI-enabled platforms created around specific business requirements.'),
 item('sv-priority-commerce','E-Commerce Solutions','Online stores and connected commerce experiences designed to simplify shopping, management, integrations and customer journeys.')]);
 priority.items=priority.items.map((i,n)=>({...i,actionLabel:'Learn More',destination:servicePageDestination(i.id)??null,media:structuredClone(cardMedia[n]??media)}));
 const strategy=section('services-strategy','','Digital Growth Strategy','',[
 item('sv-strategy-roadmap','Turn business goals into a connected digital roadmap.','We connect your audience, brand, marketing channels and technology requirements into a practical strategy that defines what should be built, how it should work and how it can support growth.','Digital Growth Strategy',['Brand and audience positioning','Website and e-commerce planning','SEO and digital marketing direction','GEO and AI-search readiness','AI and automation opportunities','Application and integration planning','Growth measurement']),
 item('sv-strategy-experiences','Build every customer touchpoint as one consistent system.','CODEYEA combines brand design, user experience, development, content structure and digital marketing so the website, application, online store and marketing channels work together instead of operating as separate pieces.','Connected Digital Experiences')]);strategy.media=structuredClone(media);
 const complete=section('services-complete','OUR SERVICES','Everything your business needs to move forward.','From artificial intelligence and search visibility to brand design and custom development, CODEYEA brings the essential digital services together within one connected strategy.',[
 item('sv-service-ai','AI Solutions & Business Automation','Practical AI systems and automated workflows that support teams, customers and business operations.'),
 item('sv-service-seo','SEO & GEO','Technical, content and entity-focused optimization for traditional search engines and AI-powered discovery.'),
 item('sv-service-app','Web & Mobile App Development','Custom applications, portals and digital platforms built around specific business requirements.'),
 item('sv-service-commerce','E-Commerce Solutions','Connected online shopping experiences designed for usability, management and growth.'),
 item('sv-service-website','Website Design & Development','Responsive websites that combine purposeful design, clear content and reliable development.'),
 item('sv-service-marketing','Digital Marketing','Coordinated digital channels and campaigns designed to reach and engage relevant audiences.'),
 item('sv-service-brand','Brand Design','Visual identities and brand systems that improve consistency, recognition and credibility.'),
 item('sv-service-graphic','Graphic Design','Professional digital and print materials that communicate the brand clearly.')]);
 complete.items=complete.items.map(i=>({...i,actionLabel:'Learn More',destination:servicePageDestination(i.id)??null}));
 const process=section('services-process','HOW WE WORK','A clear process. A connected result.','',[
 item('sv-step-discover','Understand the business before building the solution.','We review your goals, audience, current digital presence, internal processes and technology to identify the challenges, opportunities and highest-impact priorities.','Discover & Diagnose',['Business and audience discovery','Website and brand review','SEO and GEO opportunities','Workflow and automation assessment','Technical requirements']),
 item('sv-step-build','Turn the strategy into a connected digital solution.','We define the roadmap, create the experience and build the required website, application, e-commerce platform, marketing foundation or AI-powered workflow.','Plan, Design & Build',['Strategy and project roadmap','UX and visual design','Content structure','Development and integrations','SEO and GEO foundations','AI and automation implementation']),
 item('sv-step-launch','Launch with confidence and improve using real performance data.','We test the solution, prepare it for delivery or launch, connect the required measurement tools and identify opportunities for continued optimization and growth.','Launch, Measure & Grow',['Quality assurance','Performance and device testing','Launch or final delivery','Analytics and measurement','Optimization and scaling'])]);
 const growth=section('services-growth','CONNECTED GROWTH','Growth is not one service. It is a connected system.','CODEYEA connects artificial intelligence, marketing, design and development to help businesses attract the right audience, build trust, improve operations and create digital systems that can grow with them.',[
 item('sv-pillar-ai','Work smarter and respond faster.','AI agents, intelligent assistants and automated workflows can reduce repetitive work, improve access to business information and create faster customer experiences.','AI & Automation'),
 item('sv-pillar-marketing','Be visible wherever customers search and discover.','SEO, Generative Engine Optimization and digital marketing help businesses reach audiences through traditional search engines, AI-powered answers and relevant digital channels.','Marketing, SEO & GEO'),
 item('sv-pillar-design','Turn attention into recognition and trust.','A consistent brand and clear user experience help customers understand the business, navigate its services and feel confident taking the next step.','Design & Brand Experience'),
 item('sv-pillar-development','Turn the strategy into a measurable digital system.','Websites, applications, e-commerce platforms, integrations and analytics provide the technical foundation needed to operate, measure performance and scale.','Development & Data')]);growth.closing='When these capabilities work together, businesses gain a stronger digital presence, more efficient operations and a clearer path for sustainable growth.';
 const faq=section('services-faq','FAQ','Frequently asked questions.','',[
 item('sv-faq-services','What services does CODEYEA provide?','CODEYEA provides AI and business automation, SEO and Generative Engine Optimization, website and application development, e-commerce solutions, digital marketing, brand design and graphic design.'),
 item('sv-faq-needs','How do you determine which services a business needs?','We begin with a discovery and assessment stage to understand the business, audience, current digital presence, internal processes and growth goals before recommending a suitable combination of services.'),
 item('sv-faq-combine','Can multiple services be combined into one project?','Yes. Services can be delivered individually or combined into one connected project, such as a website with SEO and GEO foundations, AI automation, brand design and digital marketing support.'),
 item('sv-faq-ai','What can AI and business automation do for my company?','AI and automation can help organize business information, support customers, automate repetitive tasks, connect workflows and create faster access to the information teams need. The solution depends on the company’s actual processes and requirements.'),
 item('sv-faq-geo','What is the difference between SEO and GEO?','SEO improves visibility in traditional search engines. Generative Engine Optimization helps structure and strengthen content so it can be understood and referenced by AI-powered search and answer platforms. Both should work together as part of a modern visibility strategy.'),
 item('sv-faq-improve','Can CODEYEA improve an existing website, application or digital system?','Yes. We can review an existing platform and recommend whether targeted improvements, integrations, automation or a broader rebuild would be the more practical approach.'),
 item('sv-faq-time','How long does a project take?','The timeline depends on the project scope, technical requirements, content readiness, integrations and review process. A clear delivery schedule is prepared after discovery and scope confirmation.'),
 item('sv-faq-after','What happens after launch or delivery?','We complete the agreed handoff, confirm that the delivered solution has been tested and provide any included documentation or support. Maintenance, optimization, marketing and future development can be arranged separately.')]);
 const cta=section('services-cta','LET’S BUILD WHAT’S NEXT','Turn your next idea into a smarter digital system.','Whether you need AI automation, stronger SEO and GEO visibility, an e-commerce platform, a custom application or a complete digital growth strategy, CODEYEA can help define and build the right solution.');cta.actionLabel='Start Your Project';cta.destination=contact;
 return servicesPageSchema.parse({schemaVersion:1,localeId,marketId,seo:{title:'Website, SEO, Branding & AI Services | CODEYEA',description:'Explore CODEYEA services for website design, e-commerce, SEO and GEO, branding, digital marketing, apps, AI automation and technical support.'},hero:{id:'services-hero',title:'Services',media:structuredClone(media)},imageStatus:'temporary — image selection pending',sections:[intro,priority,strategy,complete,process,growth,faq,cta]});
}
