'use client';
import { useState } from 'react';
import type { Report } from '@/server/analytics-reports';

type Reports = { gaTrend: Report; gaOverview: Report; gaPages: Report; gscTrend: Report; gscQueries: Report; gscPages: Report };
const configs = [['gaTrend','ga4','date'],['gaOverview','ga4','overview'],['gaPages','ga4','pages'],['gscTrend','gsc','date'],['gscQueries','gsc','queries'],['gscPages','gsc','pages']] as const;
function values(report: Report, metric: string) { const i=report.columns.findIndex(v=>v.toLowerCase()===metric.toLowerCase()); return i<0?[]:report.rows.map(r=>Number.parseFloat(r[i])||0); }
function fmt(value:number) { return new Intl.NumberFormat('en',{notation:value>9999?'compact':'standard',maximumFractionDigits:1}).format(value); }
function Chart({report,metric,color}:{report:Report;metric:string;color:string}) { const ys=values(report,metric); if(!ys.length)return <p className="analytics-empty">Trend data is not available for this period.</p>; const max=Math.max(...ys,1),min=Math.min(...ys,0),span=Math.max(max-min,1); const points=ys.map((v,i)=>`${i/Math.max(ys.length-1,1)*100},${94-(v-min)/span*82}`).join(' '); return <svg className="analytics-chart" viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label={`${metric} over time`}><line x1="0" y1="94" x2="100" y2="94" stroke="#e4e9ed"/><polyline points={points} fill="none" stroke={color} strokeWidth="1.5" vectorEffect="non-scaling-stroke"/><text x="1" y="9" className="chart-label">{fmt(max)}</text><text x="1" y="92" className="chart-label">{fmt(min)}</text></svg>; }
function Table({report}:{report:Report}) { return report.rows.length?<div className="analytics-table-wrap"><table><thead><tr>{report.columns.map((c,i)=><th key={i}>{c}</th>)}</tr></thead><tbody>{report.rows.slice(0,8).map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>:<p className="analytics-empty">No rows were returned for this period.</p>; }
export function AnalyticsPanel() {
 const [days,setDays]=useState('28'),[reports,setReports]=useState<Reports|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){setBusy(true);setError('');setReports(null);try{const entries=await Promise.all(configs.map(async([key,source,group])=>{const response=await fetch(`/api/analytics?source=${source}&group=${group}&days=${days}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error||'Unable to load analytics');return[key,data as Report] as const;}));setReports(Object.fromEntries(entries) as Reports);}catch(e){setError(e instanceof Error?e.message:'Unable to load analytics');}finally{setBusy(false);}}
 const unavailable=reports&&Object.values(reports).find(r=>r.status!=='ready'); const gaTrend=reports?.gaTrend,gaOverview=reports?.gaOverview,gaPages=reports?.gaPages,gscTrend=reports?.gscTrend,gscQueries=reports?.gscQueries;
 const total=(r:Report|undefined,m:string)=>r?values(r,m).reduce((a,b)=>a+b,0):0; const weightedPosition=()=>{if(!gscTrend)return 0;const pos=gscTrend.columns.findIndex(v=>v.toLowerCase()==='average position'),imp=gscTrend.columns.findIndex(v=>v.toLowerCase()==='impressions');const rows=gscTrend.rows;const weight=rows.reduce((s,r)=>s+(Number(r[imp])||0),0);return weight?rows.reduce((s,r)=>s+(Number(r[pos])||0)*(Number(r[imp])||0),0)/weight:0;}; const ctr=gscTrend&&total(gscTrend,'Impressions')?total(gscTrend,'Clicks')/total(gscTrend,'Impressions')*100:0;
 const tiles=(items:[string,string,string][])=> <div className="analytics-kpis">{items.map(([label,value,color])=><article className="analytics-kpi" key={label}><span>{label}</span><strong>{value}</strong><i style={{backgroundColor:color}}/></article>)}</div>;
 return <section className="site-report analytics-dashboard"><header className="analytics-heading"><div><p className="analytics-eyebrow">Search & audience</p><h2>Analytics performance</h2><p>Real provider data from GA4 and Google Search Console. No estimates or sample metrics.</p></div><div className="analytics-controls"><label>Period<select value={days} onChange={e=>setDays(e.target.value)}>{['7','28','90'].map(d=><option value={d} key={d}>{d} days</option>)}</select></label><button onClick={load} disabled={busy}>{busy?'Loading reports…':'Refresh data'}</button></div></header>
 {error&&<p role="alert" className="analytics-alert">{error}</p>}{unavailable&&<div className={unavailable.status==='error'?'analytics-alert':'analytics-connection'} role="status"><strong>{unavailable.status==='error'?'Google could not return the report.':'Google reporting is not connected yet.'}</strong><span>{unavailable.message} {unavailable.status==='not_configured'?'Add a server-side Google access token, numeric GA4 property ID and verified Search Console property to load live results.':''}</span></div>}
 {reports&&!unavailable&&<><p className="analytics-updated">Previous {days} days, excluding today · Updated {new Date(gaTrend!.fetchedAt).toLocaleString()}</p><div className="analytics-section-title"><div><h3>GA4 audience</h3><p>Website visits and engagement</p></div><small>Google Analytics 4</small></div>
 {tiles([['Active users',fmt(total(gaOverview,'activeUsers')),'#15a886'],['Sessions',fmt(total(gaOverview,'sessions')),'#4285e8'],['Page views',fmt(total(gaOverview,'screenPageViews')),'#e45e64'],['Key events',fmt(total(gaOverview,'keyEvents')),'#965bdd']])}
 <div className="analytics-columns"><article className="analytics-card"><h3>Traffic trend</h3><Chart report={gaTrend!} metric="activeUsers" color="#2784e8"/><p className="analytics-chart-foot">Active users by day</p></article><article className="analytics-card"><h3>Top pages</h3><Table report={gaPages!}/></article></div>
 <div className="analytics-section-title"><div><h3>SEO performance</h3><p>Google Search results leading visitors to your site</p></div><small>Search Console</small></div>
 {tiles([['Search clicks',fmt(total(gscTrend,'Clicks')),'#13a887'],['Impressions',fmt(total(gscTrend,'Impressions')),'#4285e8'],['Average CTR',`${ctr.toFixed(2)}%`,'#ed6264'],['Average position',weightedPosition().toFixed(1),'#965bdd']])}
 <div className="analytics-columns"><article className="analytics-card"><h3>Search trend</h3><Chart report={gscTrend!} metric="Clicks" color="#14a887"/><p className="analytics-chart-foot">Clicks by day</p></article><article className="analytics-card"><h3>Top search queries / keywords</h3><Table report={gscQueries!}/><p className="analytics-note">Search Console may hide anonymised queries and returns leading rows, not every search term.</p></article></div><article className="analytics-card analytics-wide"><h3>Top pages in Google Search</h3><Table report={reports.gscPages}/></article>
 <details className="analytics-privacy"><summary>What is measured?</summary><p>GA4 reports aggregate usage such as pages visited, sessions, device category, broad geography and events. Search Console reports aggregate queries and pages with clicks, impressions, click-through rate and average position. These reports do not provide a visitor’s real-world identity. If Clarity is enabled separately, it can record click, scroll and pointer interactions for session playback. Never send names, email addresses or other personal details to analytics.</p></details></>}
 {!reports&&!error&&<div className="analytics-placeholder"><strong>Connect Google reporting to see live performance.</strong><span>GA4 provides site usage. Search Console provides search queries, clicks, impressions, CTR and average position.</span></div>}</section>;
}
