'use client';
import {useState,type FormEvent} from 'react';
import {industryDetailSchema,type DetailSection} from '@/schemas/industry-detail';
import {SeoEditor} from './seo-editor';
import type {AboutMedia} from '@/schemas/about';import type {Page} from './types';import {MediaPicker} from './media-picker';import {assetUrl} from '@/content/homepage-assets';
function Text({label,value,onChange,long=false}:{label:string;value:string;onChange:(v:string)=>void;long?:boolean}){return <label className="field-label">{label}{long?<textarea rows={6} value={value} onChange={e=>onChange(e.target.value)}/>:<input value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
function Media({value,onChange}:{value:AboutMedia;onChange:(m:AboutMedia)=>void}){const [open,setOpen]=useState(false);return <div className="cms-media"><img src={assetUrl(value.mediaId)} alt="Selected section media" style={{maxWidth:240}}/><button type="button" onClick={()=>setOpen(true)}>Choose image</button><Text label="Image alt text" value={value.alt} onChange={alt=>onChange({...value,alt})}/><label><input type="checkbox" checked={value.decorative} onChange={e=>onChange({...value,decorative:e.target.checked})}/>Decorative image</label>{(['focalX','focalY','tabletFocalX','tabletFocalY','mobileFocalX','mobileFocalY'] as const).map((key,n)=><label className="field-label" key={key}>{['Desktop horizontal','Desktop vertical','Tablet horizontal','Tablet vertical','Mobile horizontal','Mobile vertical'][n]} focal position<input type="range" min={0} max={100} value={value[key]} onChange={e=>onChange({...value,[key]:Number(e.target.value)})}/></label>)}{open&&<MediaPicker selected={value.mediaId} close={()=>setOpen(false)} choose={(mediaId,defaults)=>{onChange({...value,...defaults,mediaId});setOpen(false)}}/>}</div>}
export function IndustryDetailEditor({draft,dirty,busy,canEdit,onChange,onSave}:{draft:Page;dirty:boolean;busy:boolean;canEdit:boolean;onChange:(p:Page)=>void;onSave:(e:FormEvent)=>void}){
 const c=draft.industryDetail!,[selected,setSelected]=useState('hero'),[error,setError]=useState(''),[preview,setPreview]=useState(false),[width,setWidth]=useState(1440);const section=c.sections.find(s=>s.id===selected);
 const update=(next:typeof c)=>{setPreview(false);onChange({...draft,industryDetail:next})};const change=(next:DetailSection)=>update({...c,sections:c.sections.map(s=>s.id===next.id?next:s)});
 function submit(e:FormEvent){const result=industryDetailSchema.safeParse(c);if(!result.success){e.preventDefault();setError(result.error.issues.map(i=>i.path.join('.')+': '+i.message).join(' · '));return}setError('');onSave(e)}
 const bounds=section?({strip:[4,5],needs:[3,4],services:[4,8],growth:[4,4],process:[4,4],outcomes:[3,4],faq:[5,7],related:[2,12]} as Record<string,number[]>)[section.type]:undefined;
 return <form onSubmit={submit}><div className="editor-toolbar cms-sticky"><strong>{dirty?'Unsaved changes':'Private saved '+c.hero.title+' draft'} · v{draft.version}</strong><div className="cms-actions"><button className="button" disabled={!dirty||busy||!canEdit}>Save draft</button><button type="button" className="button secondary" disabled={dirty||busy} onClick={()=>setPreview(!preview)}>Preview</button></div></div>{error&&<p role="alert">{error}</p>}{preview&&<section className="cms-preview"><label>Preview width<select value={width} onChange={e=>setWidth(Number(e.target.value))}>{[1440,768,390,320].map(w=><option key={w}>{w}</option>)}</select></label><a href={"/preview/industries/"+c.slug} target="_blank" rel="noreferrer">Open saved {c.hero.title} preview</a><div style={{overflow:'auto'}}><iframe title={"Saved "+c.hero.title+" preview"} src={"/preview/industries/"+c.slug} style={{width,height:850,border:0}}/></div></section>}
 <div className="editor-grid"><nav className="section-list" aria-label={c.hero.title+" sections"}><button type="button" className="section-item" aria-pressed={selected==='hero'} onClick={()=>setSelected('hero')}>{c.hero.enabled===false?'Hero · Hidden':'Hero · Visible'}</button>{c.sections.map((s,n)=><button type="button" className="section-item" key={s.id} aria-pressed={selected===s.id} onClick={()=>setSelected(s.id)}>{n+1}. {s.label} · {s.enabled?'Visible':'Hidden'}</button>)}</nav><section className="editor-fields"><fieldset disabled={!canEdit||busy} style={{border:0,padding:0,minWidth:0}}>
 {selected==='hero'?<><h2>{c.hero.title} Hero</h2>{c.seo&&<><Text label="SEO title" value={c.seo.title} onChange={title=>update({...c,seo:{...c.seo!,title}})}/><Text label="SEO description" value={c.seo.description} long onChange={description=>update({...c,seo:{...c.seo!,description}})}/></>}<p>CODEYEA is fixed. The approved shared Hero layout is developer-controlled.</p><label><input type="checkbox" checked={c.hero.enabled!==false} onChange={e=>update({...c,hero:{...c.hero,enabled:e.target.checked}})}/>Show Hero section</label><Text label="Page H1" value={c.hero.title} onChange={title=>update({...c,hero:{...c.hero,title}})}/><h3>Hero image</h3><Media value={c.hero.media} onChange={media=>update({...c,hero:{...c.hero,media}})}/><label><input type="checkbox" checked={c.hero.temporaryMedia} onChange={e=>update({...c,hero:{...c.hero,temporaryMedia:e.target.checked}})}/>Temporary media for pre-launch replacement</label></>:section&&<><h2>{section.label}</h2><p>Stable ID: {section.id}. Section order and layout are fixed.</p><label><input type="checkbox" checked={section.enabled} onChange={e=>change({...section,enabled:e.target.checked})}/>Show this section</label>
 {section.type==='related'&&c.schemaVersion===2&&<p>Links are read from the enabled Industries collection. Edit names, order and destinations on the Industries page; This page does not duplicate that collection.</p>}{(['label','heading','body','actionLabel','destination'] as const).map(key=><Text key={key} label={'Section '+key} value={section[key]} long={key==='body'} onChange={v=>change({...section,[key]:v})}/>)}{section.type==='services'&&<Text label="Service list label" value={section.listLabel??'OUR SERVICES'} onChange={listLabel=>change({...section,listLabel})}/>}<p>Separate paragraphs with a blank line. Destinations stay inactive until an implemented page is available. Leave missing destinations empty.</p>
 {(c.schemaVersion===1||["overview","needs","imageBreak","cta"].includes(section.type))&&<><h3>{({overview:"Overview background image",needs:"Needs main image",imageBreak:"Full-width image",cta:"CTA background image"} as Record<string,string>)[section.type]??"Section image"}</h3><label><input type="checkbox" checked={Boolean(section.media)} onChange={e=>change({...section,media:e.target.checked?{...c.hero.media}:undefined})}/>Include image</label>{section.media&&<Media value={section.media} onChange={media=>change({...section,media})}/>}</>}{c.schemaVersion===2&&section.type==="needs"&&<><h3>Pillars background image</h3><p>{section.pillarMedia?"This image is controlled separately.":"Currently using the Overview image. Choose a separate image to control it independently."}</p><Media value={section.pillarMedia??c.sections.find(s=>s.type==="overview")?.media??c.hero.media} onChange={pillarMedia=>change({...section,pillarMedia})}/></>}<label><input type="checkbox" checked={section.temporaryMedia} onChange={e=>change({...section,temporaryMedia:e.target.checked})}/>Temporary media for pre-launch replacement</label>
 {section.items.map((item,n)=><details key={item.id}><summary>{item.title}</summary><p>Stable ID: {item.id}</p>{section.type==='strip'&&<><h3>Strip image {n+1}</h3><Media value={item.media??c.hero.media} onChange={media=>change({...section,items:section.items.map(i=>i.id===item.id?{...i,media}:i)})}/></>}{(['title','body','actionLabel','destination'] as const).map(key=><Text key={key} label={'Item '+key} value={item[key]} long={key==='body'} onChange={v=>change({...section,items:section.items.map(i=>i.id===item.id?{...i,[key]:v}:i)})}/>)}<div className="cms-actions"><button type="button" disabled={n===0} onClick={()=>{const items=[...section.items];[items[n-1],items[n]]=[items[n],items[n-1]];change({...section,items})}}>Move up</button><button type="button" disabled={!bounds||section.items.length<=bounds[0]} onClick={()=>change({...section,items:section.items.filter(i=>i.id!==item.id)})}>Remove item</button></div></details>)}{bounds&&!(section.type==='related'&&c.schemaVersion===2)&&<button type="button" disabled={section.items.length>=bounds[1]} onClick={()=>change({...section,items:[...section.items,{id:crypto.randomUUID(),title:'New item',body:'',actionLabel:'',destination:'',...(section.type==='strip'?{media:{...c.hero.media}}:{})}]})}>Add item</button>}
 </>}
 </fieldset></section></div></form>;
}
