"use client";
import {useEffect,useRef,useState} from 'react';
import {homepageAssets,assetUrl} from '@/content/homepage-assets';
import {StockSearch} from './stock-search';
type Asset={source?:{provider:string;providerId:string;sourcePageUrl:string;contributor:string;contributorUrl:string|null;originalWidth:number;originalHeight:number;importedAt:string;licenseLabel:string;query:string;approvalStatus:string};fileHash?:string;creator?:{name:string};id:string;filename:string;width:number;height:number;mimeType:string;size:number;alt:string;focalX:number;focalY:number;creatorId:string;createdAt:string;archivedAt:string|null;state:string;version:number};
type Usage={drafts:{id:string;title:string;sections:string[]}[];published:{id:string;title:string;sections:string[]}[];revisions:{pageId:string;version:number}[];publications:{pageId:string;version:number}[]};
export function MediaPicker({selected,choose,close}:{selected:string;choose:(id:string,defaults?:{width:number;height:number;alt:string;decorative:boolean;focalX:number;focalY:number})=>void;close:()=>void}){
 const [stockOpen,setStockOpen]=useState(false),[stockSearchEnabled,setStockSearchEnabled]=useState(false),[libraryRefresh,setLibraryRefresh]=useState(0);
 const inspection=useRef(0);const dialog=useRef<HTMLDialogElement>(null),upload=useRef<XMLHttpRequest|null>(null);const [query,setQuery]=useState(''),[filter,setFilter]=useState('active'),[assets,setAssets]=useState<Asset[]>([]),[canManage,setCanManage]=useState(false),[nextCursor,setNextCursor]=useState<string|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[progress,setProgress]=useState<number|null>(null),[busy,setBusy]=useState(false),[inspecting,setInspecting]=useState(false),[detail,setDetail]=useState<Asset|null>(null),[usage,setUsage]=useState<Usage|null>(null);
 useEffect(()=>{const el=dialog.current;el?.showModal();return()=>{el?.close();inspection.current++;upload.current?.abort();};},[]);
 useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>{fetch('/api/media?q='+encodeURIComponent(query),{signal:controller.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);setAssets(data.assets);setCanManage(data.canManage);setStockSearchEnabled(data.stockSearchEnabled===true);setNextCursor(data.nextCursor);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});},150);return()=>{clearTimeout(timer);controller.abort();};},[query,libraryRefresh]);
 async function loadMore(){setBusy(true);try{const r=await fetch('/api/media?q='+encodeURIComponent(query)+'&cursor='+encodeURIComponent(nextCursor!));const data=await r.json();if(!r.ok)throw new Error(data.error);setAssets(v=>[...v,...data.assets]);setNextCursor(data.nextCursor);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function inspect(asset:Asset){if(busy)return;const ticket=++inspection.current;setInspecting(true);setDetail(asset);setUsage(null);setError('');try{const r=await fetch('/api/media/'+asset.id);const data=await r.json();if(!r.ok)throw new Error(data.error);if(ticket!==inspection.current)return;setDetail(data.asset);setUsage(data.references);}catch(e){if(ticket===inspection.current)setError((e as Error).message);}finally{if(ticket===inspection.current)setInspecting(false);}}
 function send(file:File){setError('');setMessage('');if(file.size>8*1024*1024){setError('Maximum upload size is 8 MiB.');return;}const xhr=new XMLHttpRequest();upload.current=xhr;setProgress(0);xhr.open('POST','/api/media');xhr.setRequestHeader('Content-Type','application/octet-stream');xhr.setRequestHeader('X-File-Name',encodeURIComponent(file.name));xhr.upload.onprogress=e=>{if(e.lengthComputable)setProgress(Math.round(e.loaded/e.total*100));};xhr.onerror=()=>{setError('Upload failed. Your page edits are unchanged.');setProgress(null);};xhr.onload=()=>{setProgress(null);let result;try{result=JSON.parse(xhr.responseText);}catch{setError('Unable to process this upload.');return;}if(xhr.status!==201){setError(result.error??'Upload failed');return;}setAssets(v=>[result.asset,...v]);setMessage('Image uploaded privately. Select it, then save the page draft.');void inspect(result.asset);};xhr.send(file);}
 async function action(kind:'metadata'|'archive'|'recover'|'cleanup'){if(!detail||inspecting)return;if(kind==='archive'&&!confirm('Archive this unused image? It can be recovered later.'))return;setBusy(true);setError('');try{const r=await fetch('/api/media/'+detail.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:kind,expectedVersion:detail.version,...(kind==='metadata'?{alt:detail.alt,focalX:detail.focalX,focalY:detail.focalY}:{})})});const data=await r.json();if(!r.ok)throw new Error(data.error);setAssets(v=>kind==='cleanup'?v.filter(a=>a.id!==detail.id):v.map(a=>a.id===data.id?data:a));if(kind==='cleanup'){setDetail(null);setUsage(null);}else setDetail(current=>current?.id===data.id?{...current,...data}:current);setMessage(kind==='metadata'?'Image defaults saved. Existing draft and published references are unchanged.':kind==='archive'?'Image archived.':'Image recovered or cleanup completed.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <dialog ref={dialog} className="cms-media-dialog" aria-label="Media library" onCancel={e=>{e.preventDefault();if(progress===null)close();}}><div className="section-heading"><h2>Media library</h2><button type="button" disabled={progress!==null} onClick={close}>Close media library</button></div>
 <p className="small">Uploads are private until a saved page using them is explicitly published. Original recovered assets are read-only; the footer background is protected.</p>
 <div role="alert">{error}</div><p aria-live="polite">{message}</p>
 {canManage&&<div className="cms-upload"><label className="field-label" htmlFor="image-upload">Upload raster image</label><input id="image-upload" type="file" accept="image/jpeg,image/png,image/webp" disabled={progress!==null} onChange={e=>{const file=e.target.files?.[0];if(file)send(file);e.target.value='';}}/><p className="small">JPEG, PNG or WebP · max 8 MiB · 16–8192 px per side · max 24 megapixels. No SVG or animation. Files are validated and converted to optimized WebP.</p>{progress!==null&&<><progress value={progress} max={100} aria-label="Upload progress"/><span>{progress===100?'Processing image…':progress+'% uploaded'}</span></>}</div>}
 {canManage&&(stockSearchEnabled?<button type="button" disabled={progress!==null} onClick={()=>setStockOpen(v=>!v)}>Search free stock</button>:<p className="small" role="status">External stock search is paused during the design milestone.</p>)}
 {stockSearchEnabled&&stockOpen&&<StockSearch close={()=>setStockOpen(false)} onImported={()=>setLibraryRefresh(v=>v+1)}/>} 
 <label className="field-label" htmlFor="media-search">Find image</label><input id="media-search" value={query} onChange={e=>setQuery(e.target.value)}/><label className="field-label" htmlFor="media-filter">Library filter</label><select id="media-filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">Active images</option><option value="uploaded">Uploaded images</option><option value="recovered">Recovered originals</option><option value="archived">Archived images</option><option value="cleanup">Pending cleanup</option></select>
 {detail&&<section className="cms-media-details" aria-label="Image details"><h3>{detail.filename}</h3>{detail.state==='READY'&&<img src={'/api/media/'+detail.id+'/medium'} alt="Image preview" style={{objectPosition:detail.focalX+'% '+detail.focalY+'%'}}/>}<p>{detail.width} × {detail.height} · {detail.mimeType} · {(detail.size/1024).toFixed(1)} KB</p><p className="small">Uploaded {new Date(detail.createdAt).toLocaleString()} · Creator {detail.creator?.name??detail.creatorId}</p><label className="field-label" htmlFor="library-alt">Default alt text</label><input id="library-alt" maxLength={300} value={detail.alt} disabled={!canManage||busy||inspecting} onChange={e=>setDetail({...detail,alt:e.target.value})}/>{(['focalX','focalY'] as const).map((key,i)=><label className="field-label" key={key}>Default focal {i===0?'horizontal':'vertical'}: {detail[key]}%<input aria-label={'Default focal '+(i===0?'horizontal':'vertical')} type="range" min={0} max={100} value={detail[key]} disabled={!canManage||busy||inspecting} onChange={e=>setDetail({...detail,[key]:Number(e.target.value)})}/></label>)}
 {detail.source&&<section aria-label="Stock source metadata"><h4>Stock source</h4><p>{detail.source.provider} · {detail.source.contributor} · {detail.source.approvalStatus}</p><a href={detail.source.sourcePageUrl} target="_blank" rel="noopener noreferrer">Original source page</a>{detail.source.contributorUrl&&<p><a href={detail.source.contributorUrl} target="_blank" rel="noopener noreferrer">Contributor profile</a></p>}<p>{detail.source.licenseLabel}</p><p>Original: {detail.source.originalWidth} × {detail.source.originalHeight} · Imported: {detail.width} × {detail.height}</p><p>Imported {new Date(detail.source.importedAt).toLocaleString()} · Search: {detail.source.query}</p><p>Provider ID: {detail.source.providerId}</p><p style={{overflowWrap:"anywhere"}}>File hash: {detail.fileHash}</p></section>}
 {usage?<details open><summary>Where this image is used</summary><p>Saved drafts: {usage.drafts.map(p=>p.title+(p.sections?.length?' — '+p.sections.join(', '):'')).join(', ')||'None'}</p><p>Published pages: {usage.published.map(p=>p.title+(p.sections?.length?' — '+p.sections.join(', '):'')).join(', ')||'None'}</p><p>{usage.revisions.length} historical revisions · {usage.publications.length} publication records</p></details>:<p>Checking references…</p>}
 <div className="cms-actions">{detail.state==='READY'&&!detail.archivedAt&&<button type="button" className="button" disabled={busy||inspecting||progress!==null} onClick={()=>choose(detail.id,{width:detail.width,height:detail.height,alt:detail.alt,decorative:!detail.alt.trim(),focalX:detail.focalX,focalY:detail.focalY})}>Use image</button>}{canManage&&detail.state==='READY'&&<><button type="button" disabled={busy||inspecting} onClick={()=>action('metadata')}>Save image defaults</button><button type="button" disabled={busy||inspecting||!usage||(!detail.archivedAt&&!!(usage.drafts.length||usage.published.length||usage.publications.length))} onClick={()=>action(detail.archivedAt?'recover':'archive')}>{detail.archivedAt?'Recover image':'Archive image'}</button></>}{canManage&&detail.state!=='READY'&&<button type="button" disabled={busy||inspecting} onClick={()=>action('cleanup')}>Retry cleanup</button>}<button type="button" disabled={busy} onClick={()=>{inspection.current++;setInspecting(false);setDetail(null);}}>Close image details</button></div></section>}
 <div className="cms-media-grid">{['active','recovered'].includes(filter)&&homepageAssets.filter(a=>a.filename.includes(query.toLowerCase())).map(asset=><button type="button" key={asset.id} aria-label={asset.filename} disabled={busy||progress!==null} aria-pressed={selected===asset.id} onClick={()=>choose(asset.id)}><img src={asset.src} alt="" loading="lazy"/><span>{asset.filename}</span><small>Recovered · read-only</small></button>)}{assets.filter(a=>filter==='cleanup'?a.state!=='READY':filter==='archived'?!!a.archivedAt:filter!=='recovered'&&!a.archivedAt&&a.state==='READY').map(asset=><button type="button" key={asset.id} aria-pressed={selected===asset.id} onClick={()=>inspect(asset)}>{asset.state==='READY'&&<img src={'/api/media/'+asset.id+'/thumb'} alt="" loading="lazy"/>}<span>{asset.filename}</span><small>{asset.archivedAt?'Archived':asset.state==='READY'?'Uploaded':asset.state}</small></button>)}</div>{nextCursor&&<button type="button" disabled={busy} onClick={loadMore}>Load more images</button>}
 </dialog>;
}
